### ISSUE TITLE
firekylin多域名共存

### ISSUE THREAD

**Issue by beyourhero** [75team/firekylin#104]
假设有blog 虚拟目录  work虚拟目录  default虚拟目录,
将firekylin放置blog目录下，并用80端口，通过blog.xxx.com访问
而work将通过work.xxx.com
default通过xxx.com访问，
请问如何配置

**Comment by lizheming** [comment]
nginx 配置文件中不同的 server 用不同的 server_name 并对应不同的 root 目录就好了，比如说

```
server {
    listen 80;
    server_name blog.xxx.com;
    root /www/blog;
}

server {
    listen 80;
    server_name work.xxx.com;
    root /www/work;
}
```

具体可以搜索“nginx 多域名”相关的关键词，例如：http://xiugq.blog.51cto.com/813544/693448
