### ISSUE TITLE
react版本是不是低了

### ISSUE THREAD

**Issue by wwhgtt** [75team/firekylin#109]
我习惯用redux-react   看到jsx里面有if?

**Comment by lizheming** [comment]
react 版本没升呢，还是 0.14.8，15没有比较大的更新就不跟了，等需要升级的时候再说。jsx 里面只能做三目不能写 if 呀，你在哪里看到的？我们用的是 reflux，其实感觉都差不多，嘿嘿

**Comment by wwhgtt** [comment]
看错了  不好意思。。。
