### ISSUE TITLE
提示mysql password错误？

### ISSUE THREAD

**Issue by henryzp** [75team/firekylin#112]
npm start，报这个错误：

![image](https://cloud.githubusercontent.com/assets/3849702/15998691/e87b4412-3172-11e6-8591-ff6f5c06461c.png)

**Comment by lizheming** [comment]
这看着像是没有用户名啊，你检查下 db.js 然后重启下试试

**Comment by henryzp** [comment]
@lizheming 用安装版就可以了。。我用的是git clone下来的。。

**Comment by lizheming** [comment]
@henryzp OK，如果不对程序进行开发阿德话尽量使用安装版哈~ 感谢~
