### ISSUE TITLE
无法访问admin路径，即无法进入后台

### ISSUE THREAD

**Issue by henryzp** [75team/firekylin#113]
当我访问http://localhost:8360/admin

![image](https://cloud.githubusercontent.com/assets/3849702/15999137/18854db2-3176-11e6-9703-c479f550b7dd.png)

另外我这边命令npm run webpack报错，

![image](https://cloud.githubusercontent.com/assets/3849702/15999153/3c3b75ba-3176-11e6-9cc5-3d29f514a295.png)

求指点

**Comment by Jerret321** [comment]
webpack --config webpack.config.babel.js

**Comment by lizheming** [comment]
是哪个资源没有，截个全图，安装版本是已经编译好了的，不用再重新编译。

**Comment by henryzp** [comment]
@lizheming 

![image](https://cloud.githubusercontent.com/assets/3849702/15999522/e552509a-3178-11e6-96f2-2b8b89504566.png)

webpack那个问题，安装版本因为没有webpack的配置文件，所以就像你所说的，不用管。。但上面的问题，帮我看看吧？

**Comment by lizheming** [comment]
我上了一个新版，你重新下载覆盖一下试一下。

**Comment by henryzp** [comment]
已经搞定了，谢谢！

@lizheming ，建议在readme里面，把安装包文件改一下。。

不然其他人还是会踩这个坑，thx

**Comment by lizheming** [comment]
安装包还是原来的那个。另外，你是不是用之前的数据库了，0.12.4 数据库新加了一条数据，你要导入下数据才行。

**Comment by henryzp** [comment]
好的。。
