### ISSUE TITLE
关于推送的几个问题

### ISSUE THREAD

**Issue by Jerret321** [75team/firekylin#114]
1、众成翻译，推送过来的是articleID， firekylin_id，推送是通过 firekylin来抓取 众成翻译的文章 然后再post到firekylin
2、如果1成立，那么1中关于抓取文章的代码在哪里
3、firkelin后台后 专门的推送池子么，前面的没有推过去后面的就不推， 我试了下推送，推送列表一直木有。

麻烦告知2，3代码在哪里，或者有空讲下原理，只是好奇。

**Comment by lizheming** [comment]
推送直接推送的是内容，不是id，所以不会有zcfy相关的逻辑，也没有推送队列。具体你可以查看 https://github.com/lizheming/push-to-firekylin 项目就懂了

**Comment by Jerret321** [comment]
大赞效率。 我学习哈
