### ISSUE TITLE
线上后台文章修改之后，前台未展示了？

### ISSUE THREAD

**Issue by henryzp** [75team/firekylin#115]
线上一开始文章发布之后，能够正常显示的，但在修改之后，就显示不了了。对应的路径也无法跳过去。。

请问一般会是什么原因？

另，想问一个问题是：怎么写博客摘要。。或者说前台只显示一部分，只有当阅读全文的时候，才显示全部？

**Comment by lizheming** [comment]
无法跳过去是什么意思？有没有demo我去看一下？
摘要就是写 `<!--more-->` 然后之前的就是摘要，我以为这个应该写博客的人都知道呢。。。。

**Comment by henryzp** [comment]
好吧，我博客写的少。。

![image](https://cloud.githubusercontent.com/assets/3849702/16069357/656ae64c-3300-11e6-84ca-7fedb7957dcf.png)

**Comment by henryzp** [comment]
我后台有两篇文章，但前台只显示一篇。。

不知道什么情况。。修改hello，是正常的

**Comment by lizheming** [comment]
第一篇文章的创建日期怎么成了 6月15日 21:50 了，你自己选择的么？

**Comment by henryzp** [comment]
应该是服务器那边的吧

**Comment by henryzp** [comment]
或者你能不能留个QQ，我直接给你地址，帮我看一下吧？

**Comment by lizheming** [comment]
那你检查下服务器时间吧，不显示是因为你这篇文章的时间还没到，属于未来发布的文章。

**Comment by henryzp** [comment]
懂了，只要自己修改一下发布的时间就行了。。

**Comment by lizheming** [comment]
但是我现在不是很懂你为什么创建时间会是那个时间，如果不是你自己选择的话那应该就有问题了，你能确认下你的服务器时间是正确的么？

**Comment by henryzp** [comment]
那个是国外的主机，所以时间上估计有问题，我要联系一下客服那边

**Comment by lizheming** [comment]
OK，那我先关闭这个 issue 了，有后续的进展可以继续在这个 issue 中讨论。

**Comment by henryzp** [comment]
@lizheming ，linux的是UTC时间，相差八个小时。。

然后你知道这个怎么处理比较好吗？是用命令解决，还是说联系客服，让对方帮忙处理一下？

**Comment by lizheming** [comment]
你没办法 ssh 登录机器么？这个直接设置下主机的时区就可以解决的。如果不能的话就联系客服吧。

**Comment by henryzp** [comment]
用了：

```
sudo cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
sudo ntpdate time.windows.com
```

查看date -R，显示的时区是东八区了。。但是我博客修改之后，就无法显示，然后一编辑发现时间还是不对。。

linux不会是需要重启吧？

**Comment by fegg** [comment]
。。。。我怎么订阅了你们的，你们这样聊下去不是办法哦～

**Comment by henryzp** [comment]
发现node重启之后，就可以了。。我去。。

**Comment by henryzp** [comment]
@fegg ，不好意思，哥们，打扰到你了。。

**Comment by jiespring** [comment]
我用的pm2，怎么重启你说的node？https://github.com/firekylin/firekylin/issues/326

**Comment by lizheming** [comment]
@jiespring `pm2 restart firekylin `即可，firelykin 是你的守护进程名称，可以通过 `pm2 list`查看

**Comment by jiespring** [comment]
文章默认显示时间已纠正好了。
