### ISSUE TITLE
nginx 静态资源 403

### ISSUE THREAD

**Issue by ystarlongzi** [75team/firekylin#117]
我这里在配置 nginx 时，发现当对静态资源开启缓存时，请求会响应 403。代码位于 [firekylin/nginx.conf[L38-41]](https://github.com/75team/firekylin/blob/master/nginx.conf#L38-L41)，如下：
```
 location ~ /static/ {
        etag         on;
        expires      max;
    }
```

在网上查了下说是有两种原因：
1. 将 nginx 的 `user` 配置为当前用户。因为当前用户是 root，然后我就配置了 `user root`，响应还是 403
2. 将文件夹权限设置为 777。然后我也将 /static 文件夹权限也设置为 777 了，但响应还是 403

不知道有其他人遇到过类似的问题没？

**Comment by lizheming** [comment]
没有这个问题，这个问题我不是非常清楚，你看看有没有重启 nginx 以及 static 文件夹的所属用户组组有没有问题。

**Comment by ystarlongzi** [comment]
好的，谢谢。我在研究下

**Comment by ystarlongzi** [comment]
应该是文件夹权限问题，问题已解决

**Comment by SvenZhao** [comment]
请问一下 @ystarlongzi 您是怎么解决的 我在ubuntu16.04的服务器上也遇到了相同的问题 解决方式 是关闭了静态缓存 直接用域名：端口 访问时不会被禁止的

**Comment by ystarlongzi** [comment]
你把 nginx 关闭后，再重启试一下


发自 网易邮箱大师
在2016年09月08日 22:38，SvenZhao 写道:

请问一下 @ystarlongzi 您是怎么解决的 我在ubuntu16.04的服务器上也遇到了相同的问题 解决方式 是关闭了静态缓存 直接用域名：端口 访问时不会被禁止的

**Comment by haodalong** [comment]
请问centos7如何解决该问题？

**Comment by Jerret321** [comment]
firekylin默认没有编译 admin(后台)的js 所有www/static下面没有js 所以会出现 403， 需要检查js文件存在 且有可访问权限即可！

**Comment by lizheming** [comment]
@Jerret321 你说的是开发版吧，安装的版本默认就是编译好的，不需要用户编译。

**Comment by Jerret321** [comment]
@lizheming 恩 我用的开发版 改了一些东西

**Comment by jiespring** [comment]
https开启后，静态文件static又不能访问了，修改了权限和所有者还是不行。？？

**Comment by RuthlessPotato** [comment]
@SvenZhao 同样使用端口 访问时不会被禁止的，后来您是怎么解决的
