### ISSUE TITLE
升级文档笔误和RSS时间格式的问题

### ISSUE THREAD

**Issue by StevenGuanYZ** [75team/firekylin#118]
在 0.12.4 的升级文档里“数据表 fk_potions ”这里应该是 fk_options 吧。

还有就是我想反映一个问题就是生成的 RSS 文件，时间规则并不遵循 RSS 文件的规则。这会导致部分阅读器不能按照时间列出文章列表。RSS 文件的日期格式是 Wed, 23 Apr 2008 19:27:19 +0800 。

**Comment by lizheming** [comment]
感谢指出，已经修正了。
RSS 时间我上回看了 RSS 标准，标准上指出只要是一个符合规范的时间格式就可以，我看了下我这个是 OK 的诶。

**Comment by StevenGuanYZ** [comment]
诶，但是 imququ 的博客是我说的那个格式的。我也看了一下 http://www.welefen.com ，同样也是在 Safari 下订阅， imququ 的能根据时间排好。但是我和 welefen 的都去到了最后面。那可能是 Safari 的锅。

**Comment by lizheming** [comment]
这个时间的问题我再调研一下吧

**Comment by StevenGuanYZ** [comment]
好滴，谢谢！！

**Comment by qgy18** [comment]
我是按照这个说明文档输出的时间格式：

https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

这是 w3 的 feed 在线验证器：

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.welefen.com%2Frss.html

On Sat, Jun 18, 2016 at 10:52 PM, StevenGuanYZ <notifications@github.com>
wrote:

> 好滴，谢谢！！
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/75team/firekylin/issues/118#issuecomment-226946498>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AARauYeKWrv70tbt8POT4gGifDrMFU3Wks5qNAZFgaJpZM4I47Pc>
> .
>



-- 
非常感谢~

屈光宇（ImQuQu.com）

**Comment by lizheming** [comment]
@qgy18 好吧，那我按照这个提示的修改下吧，谢谢屈屈... 我上回看到的 rss 标准里没说的这么清楚，只给了一个时间的 rfc 给我…
