### ISSUE TITLE
build.sh 里处理theme的index.php那里获取呀？

### ISSUE THREAD

**Issue by changfuguo** [75team/firekylin#119]
$PHP $STC_PATH/index.php ${path} test online config_theme.php output.theme;

请问该index.php 如何获取呀？

**Comment by lizheming** [comment]
开发版你们是用不了的，那个是我们的一个私有的 PHP 项目，如果是安装开发版的话可以不用管 build.sh 脚本。

**Comment by changfuguo** [comment]
问题是 我想clone代码自己build的话就木有办法了？

**Comment by changfuguo** [comment]
开发版本中，自己想build的话，直接注释处理index.php的theme代码可以吧？

**Comment by lizheming** [comment]
还需要注释掉最后的上传文件相关代码啊。不过你为什么要 build 呢？build 只是去除了开发依赖而已。
