### ISSUE TITLE
clone安装无法进入后台，显示用户名密码错误

### ISSUE THREAD

**Issue by dangyanglim** [75team/firekylin#122]
~~~

**Comment by dangyanglim** [comment]
填写admin,admin12345678不行

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/issues/64#issuecomment-228689646

**Comment by dangyanglim** [comment]
好像是因为数据库没有admin用户，怎么插入数据到数据表里？我直接插入name和password不行

**Comment by dangyanglim** [comment]
insert into fk_user(name,password,type,email,status,create_time,create_ip,last_login_time,last_login_ip) values('admin','admin12345678',1,'350082722@qq.com',1,'2009-9-9 23:22:11','192.168.1.1','2009-9-9 23:22:11','192.168.1.1');

**Comment by dangyanglim** [comment]
insert into fk_user(name,password,type,email,status,create_time,create_ip,last_login_time,last_login_ip) values('admin','admin12345678',1,'88888@qq.com',1,'2009-9-9 23:22:11','192.168.1.1','2009-9-9 23:22:11','192.168.1.1');

**Comment by dangyanglim** [comment]
插入数据后，登录报错json prase unexpected character at line 1 column 1 of the json data

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81%EF%BC%9F
