### ISSUE TITLE
团队在未来会弄个自带的评论功能么？

### ISSUE THREAD

**Issue by BoxMod** [75team/firekylin#125]
![image](https://cloud.githubusercontent.com/assets/16836692/16577954/900be912-42ca-11e6-9da3-e2a22a68a523.png)
赞一个！
表示不太喜欢第三方社会评论组件，不知团队未来是否弄个自带的评论组件？

**Comment by lizheming** [comment]
暂时不会去弄这个，目前会努力在自定义主题和自定义插件上，自己做评论还是比较复杂的，如果你有空的话欢迎提供相关 PR~感谢~
