### ISSUE TITLE
数据库文件（firekylin.sql）不存在，请重新下载

### ISSUE THREAD

**Issue by imvicchen** [75team/firekylin#126]
数据库文件（firekylin.sql）不存在，请重新下载
CentOS 7  阿里云，数据库连接正常，也已经创建成功，但是一直提示我不存在～

**Comment by imvicchen** [comment]
补充一下，db文件夹有firekylin.sql 这个文件

**Comment by lizheming** [comment]
安装请下载安装版 http://firekylin.org/release/latest.tar.gz ~ 仓库里面的是开发版，安装流程和安装版流程不太一样。
