### ISSUE TITLE
数据表出现问题。。。

### ISSUE THREAD

**Issue by akioseon** [75team/firekylin#127]
从服务器上到处SQL，在阿里云RDS上导入时显示这样：

========================================
【错误SQL（1）】:
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */
【失败原因】：
Variable 'sql_notes' can't be set to the value of 'NULL'

何解？

**Comment by lizheming** [comment]
导出文件里把这部分删掉就好了吧，这个不是 firekylin 的问题，是你导出 sql 加的代码的问题。

**Comment by akioseon** [comment]
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */

这段删掉么？

**Comment by lizheming** [comment]
嗯

**Comment by lizheming** [comment]
应该后面还有几个这样的，都可以删掉了

**Comment by akioseon** [comment]
我试试看

**Comment by akioseon** [comment]
不行，504.。。

**Comment by lizheming** [comment]
那你再搜搜看吧，反正这个和程序的关系不大，就是你自己 sql 导入导出的问题，Google 上我搜到有类似的问题了，你自己也搜搜看

**Comment by akioseon** [comment]
OK   我再试试看吧
