### ISSUE TITLE
添加文章标签重复

### ISSUE THREAD

**Issue by xuexb** [75team/firekylin#129]
如：[标题 - 前端小武的博客](https://xuexb.com/tags/)

发现有的不重复，有的重复，是我添加的姿势不对？我记得有的是在标签下拉提示里选择的，有的是直接输入回车的

```
系统概况

服务器系统：linux
Node.js版本：5.7.0
V8引擎版本：4.6.85.31
MySQL版本：5.1.73
ThinkJS版本：2.2.5
FireKylin版本：0.12.5
```

**Comment by lizheming** [comment]
你看下你的 tag 是不是的确有很多重复的？输入的如果是已经存在的，应该会直接选存在的那个吧。

**Comment by xuexb** [comment]
数据库里`tags`表是唯一的，并且在url中`/tags/name`中是正常显示数据（多数量）的，就是标签有很多个

**Comment by lizheming** [comment]
@xuexb 更新到 0.12.7 吧，这个问题 fix 了。
