### ISSUE TITLE
标签显示少了一个

### ISSUE THREAD

**Issue by litterzhang** [75team/firekylin#131]
添加了2个标签，在一篇文章里同时用了两个标签。
标签页面只显示了一个标签，标签后面的文章数量显示：2

**Comment by lizheming** [comment]
那你能确认下标签是否添加进去了么？以及文章数？

**Comment by litterzhang** [comment]
我已经解决了。数据库中数据都正常，是查询过程出问题了。联表查询时，后join的字段，覆盖了先join的字段（字段名一样，pathname）。

**Comment by lizheming** [comment]
啊，你太棒叻！那你能提个 pr 么~让大家都受益一下 =w= 谢谢~~
