### ISSUE TITLE
安装出错提示 sql文件不存在,sql文件实际是存在的。

### ISSUE THREAD

**Issue by chenwenli** [75team/firekylin#133]
![image](https://cloud.githubusercontent.com/assets/503212/17097858/26f787ec-5292-11e6-91da-11ef46b899e1.png)

错误提示
![image](https://cloud.githubusercontent.com/assets/503212/17097906/5ccd6210-5292-11e6-99ab-c89730f49f48.png)

**Comment by lizheming** [comment]
https://github.com/75team/firekylin#安装 看安装的注释

**Comment by chenwenli** [comment]
OK,我解决了~原来clone的只是开发版~~开发版跟正式版 差别好大啊~
