### ISSUE TITLE
linux安装、npm start后，无法通过ip:8360远程访问

### ISSUE THREAD

**Issue by bi-kai** [75team/firekylin#134]
‘执行 npm start，然后访问 http://127.0.0.1:8360，根据提示填写相关信息进行安装’这一步在linux shell上如何操作？

**Comment by lizheming** [comment]
上浏览器访问 =。=|||

**Comment by bi-kai** [comment]
@lizheming 服务器上安装的thinkjs，执行`npm start`后，我本地浏览器通过ip:8360无法访问啊。

**Comment by bi-kai** [comment]
![image](https://cloud.githubusercontent.com/assets/15070379/17251516/b93285fc-55db-11e6-9791-535182cf94be.png)
linux上服务起来了，我win上通过ip:8360无法访问，这个博客系统只能win下本地玩么？？？

**Comment by qgy18** [comment]
你的 linux 是装载虚拟机里的？如果是这样，8360 端口做了映射么？

**Comment by bi-kai** [comment]
@qgy18 我是装在阿里云服务器上的，问下怎么映射呢？我本地直接访问8360无法连接。

**Comment by lizheming** [comment]
你设置下 nginx 端口映射吧，新安装包因为部分原因暂时禁止了 8360 的访问。安装过程里跳过 3 直接执行 4 和 5，然后再回到 3 操作。

**Comment by bi-kai** [comment]
@lizheming 这个可以在文档中说明下。
此外，既然默认服务的端口是8360，nginx.conf中$node_port为什么还写1234呢？默认改成：
![image](https://cloud.githubusercontent.com/assets/15070379/17277205/bce1c74a-576f-11e6-80f5-0e9689308aa4.png)
不是更合适么。

**Comment by bi-kai** [comment]
@lizheming 数据库需要自己单独安装是吧？
![image](https://cloud.githubusercontent.com/assets/15070379/17277216/0f0b2142-5770-11e6-9b8e-9b99e435855b.png)
只能用mysql么？改什么配置可以换位mongodb呢？

**Comment by lizheming** [comment]
OK，默认端口我改一下。MySQL 需要自己单独安装，应该是只支持关系型数据库，mongodb 暂无计划。

**Comment by bi-kai** [comment]
好的，谢谢。
