### ISSUE TITLE
firekylin比hexo有哪些优势？

### ISSUE THREAD

**Issue by bi-kai** [75team/firekylin#135]
一直使用hexo，主题定制化折腾了一段时间，算是能正常使用了。
看到thinkjs很不错，firekylin也是博客系统，宣称性能很强，她和hexo的横向对比如何？功能等各方面，有什么优缺点呢？

**Comment by lizheming** [comment]
hexo 是静态博客吧，firekylin 是带管理后台的类 WP/Typecho 这种动态博客，两者方向不太一样。

**Comment by bi-kai** [comment]
ok，了解。

**Comment by bi-kai** [comment]
@lizheming 我还是想问一下，hexo的静态页面访问会比较快，firekylin比hexo的优势是什么呢？
希望能罗列一下，以便选择，感谢。

**Comment by lizheming** [comment]
请搜索动态博客和静态博客的区别。

**Comment by bi-kai** [comment]
@lizheming 找了半天，真的没找到，博客内容发布基本很久都不会刷新吧，我需要一个说服别人使用的理由。

**Comment by lizheming** [comment]
不刷新？你更新一篇文章，博客首页，文章列表，所有相关的地方都需要编译更新，然后重新上传。虽然说依托 Github 用 Jekyll 可以不用那么麻烦，可是严格意义上来说 Github 的这套已经不能用纯静态博客来概括了。另外，静态博客快只是你们想象的而已，动态博客读取一次数据库哪里有你们胡乱写模板来的慢哦。  
最后如果你自己使用了也没觉得火麒麟有什么优势，那我觉得还是不要推荐给他们的好。自己都说服不了怎么说服别人呢？

**Comment by qgy18** [comment]
我觉得静态博客最麻烦的是，如果没在自己电脑面前，编辑文章太麻烦，哪怕是改正一个错别字。

而动态博客只要有浏览器，就能登录后台，随时随地修改提交。

**Comment by bi-kai** [comment]
@lizheming @qgy18 谢谢两位，在线后台编辑的方式，在团队合作中效率提升很大。免去了md收集、语法问题导致编译出错等问题。
