### ISSUE TITLE
为什么源代码里没有CSS文件？

### ISSUE THREAD

**Issue by eimhee** [75team/firekylin#136]
为什么源代码里没有CSS文件？
layout文件里有

**Comment by welefen** [comment]
这个用 localStorage 缓存技术，将静态资源缓存到 localStorage 中了。

**Comment by eimhee** [comment]
这样做有什么好处， 而不是浏览器决定下载静态资源， 
这个是不是新技术

**Comment by welefen** [comment]
这样可以让页面打开速度更快
