### ISSUE TITLE
0.12.6版本报错

### ISSUE THREAD

**Issue by henryzp** [75team/firekylin#138]
在进入/admin页面时，后台会报错：

![image](https://cloud.githubusercontent.com/assets/3849702/17375891/9b51619e-59e5-11e6-9c12-beb73d9fab4e.png)

node版本为6.2.2
npm版本为3.9.5

**Comment by welefen** [comment]
抱歉，之前发的版本有些问题。

现在应该好了，你重新下载下。

**Comment by henryzp** [comment]
@welefen ，谢谢，好了。。
