### ISSUE TITLE
npm start之后使用127.0.0.1可以访问，但是使用ip确不能访问？

### ISSUE THREAD

**Issue by fanqi** [75team/firekylin#140]
npm start之后使用127.0.0.1可以访问，但是使用ip确不能访问？

**Comment by lizheming** [comment]
因为一些问题默认禁止了远端端口访问了，做一下 nginx 代理配置吧。

**Comment by fanqi** [comment]
好吧，谢谢，今天纠结这个好久了，一直以为环境的问题。。。

**Comment by lizheming** [comment]
嗯，不好意思，我刚刚已经在首页 readme 描述中增加说明了。
