### ISSUE TITLE
分类页面分页问题

### ISSUE THREAD

**Issue by xuexb** [75team/firekylin#143]
发现我的博客里分类页面 [https://xuexb.com/cate/记事本?page=2](https://xuexb.com/cate/记事本?page=2) 其中的`page`再怎么换都是第一页的内容。而直接调用 https://xuexb.com/post/list?page=1 时换`page`是可以的，但添加上`&cate=记事本`就不行了。。。

并且我看在`model`里调用了`cache`，但我在`./runtime/cache`文件夹里并没有看到缓存文件。是我配置问题还是版本太老了？

```
系统概况

服务器系统：linux
Node.js版本：5.7.0
V8引擎版本：4.6.85.31
MySQL版本：5.1.73
ThinkJS版本：2.2.5
FireKylin版本：4.0.0
```

**Comment by xuexb** [comment]
还有后台提示的版本是`FireKylin版本：4.0.0`，而升级页面是`0.4.0 -> 0.5.0` 🎉

**Comment by lizheming** [comment]
这都什么情况.... Firekylin 现在的版本是 0.12.6 额... 哪里来的 4.0 额.... 你看下接口返回的数据是什么情况？
