### ISSUE TITLE
重装连接mysql报错

### ISSUE THREAD

**Issue by bi-kai** [75team/firekylin#145]
删除0.12.6原安装目录下的文件，使用0.12.7的新文件，npm install后，不跳转数据库安装界面，直接连接mysql，报错：
![image](https://cloud.githubusercontent.com/assets/15070379/18022907/cf533b46-6c25-11e6-8736-84d461066330.png)
如何才能重新安装？

**Comment by bi-kai** [comment]
@lizheming 我把原0.12.6目录下的文件全部删除了，重新下载了站点文件和node_modules，为什么会与第一次安装不同？难道其他目录也写了文件了么？

**Comment by lizheming** [comment]
没删全吧，根目录下有一个 .installed 隐藏文件用来标记是否安装过的。
