### ISSUE TITLE
我想修改前端页面，哪里有目录说明？

### ISSUE THREAD

**Issue by bi-kai** [75team/firekylin#146]
我想修改前端页面，哪里有目录说明？
哪些目录我能修改，哪些不能修改？

**Comment by lizheming** [comment]
www/theme 放置的是主题文件夹，默认的主题是 firekylin，每个主题都会有一个 package.json 文件用来标记主题的 meta 信息。目前有三个字段，`name` 为主题的名字，`version` 为主题的版本，`configElements` 为主题配置项元素，可以在后台显示主题配置项，是一个数组，每个元素为一个对象（具体可参考默认主题的配置），目前支持 `text`, `email`, `url`, `password`, `textarea`, `radio`, `checkbox`, `select`, `color`, `css`, `html`, `javascript` 这些类型，每个配置项的 `name` 为这个配置项存入数据库的 key，具体可参考默认主题。剩下的就是模板自己的事了，具体想要知道在模板中可以使用那些变量可以参考下默认的模板。

**Comment by bi-kai** [comment]
除了默认firekylin主题，还有其他主题可选么？还是只能在firekylin上自己定制化？

**Comment by lizheming** [comment]
只是暂时还没有开发别的主题而已，你完全可以制作自己的主题的。

**Comment by bi-kai** [comment]
好的，默认主题就已经很不错了。
