### ISSUE TITLE
安装报错，详见截图

### ISSUE THREAD

**Issue by bi-kai** [75team/firekylin#147]
安装报错，详见截图：
![image](https://cloud.githubusercontent.com/assets/15070379/18031718/22dece6a-6d20-11e6-8cf3-7ca09475c820.png)

![image](https://cloud.githubusercontent.com/assets/15070379/18031722/3e07ed2a-6d20-11e6-8dd6-85fa96a257e9.png)

![image](https://cloud.githubusercontent.com/assets/15070379/18031725/4ad71c10-6d20-11e6-8e7e-b2c2fd44083e.png)

![image](https://cloud.githubusercontent.com/assets/15070379/18031729/57829b4c-6d20-11e6-84e9-a1f83d32da5b.png)

最终页面一片空白：
![image](https://cloud.githubusercontent.com/assets/15070379/18031732/65867600-6d20-11e6-82e2-ab6a4c516f58.png)

我哪里操作错了？

主页倒是可以访问，不过，安装完，就显示成这个样式：
![image](https://cloud.githubusercontent.com/assets/15070379/18031747/ec059bf2-6d20-11e6-84a5-2086d41918fd.png)

这对么？

**Comment by lizheming** [comment]
删除数据库，删除 `.installed` 文件重新安装吧，没看到你的操作我也不知道你哪里操作错了。

**Comment by bi-kai** [comment]
@lizheming 你看哪里填错了？

![image](https://cloud.githubusercontent.com/assets/15070379/18070297/8103a230-6e7f-11e6-8ae0-52355c9a6ebf.png)

**Comment by lizheming** [comment]
数据库信息有误诶，你确认下你账号密码有没有填正确吧，还有存不存在 firekylin_blog 这个数据库。另外你的样式好像加载失败了，看看资源请求情况为啥吧，是不是 nginx 那边没配置对？

**Comment by bi-kai** [comment]
@lizheming 数据库账号密码没问题，试了好几次，都是一样的结果。
firekylin_blog数据库存在或者不存在，也都试了，没啥区别。
资源加载失败，
![image](https://cloud.githubusercontent.com/assets/15070379/18135364/45b2f590-6fd4-11e6-944c-bf2e906efa47.png)
nginx配置我没修改什么，就是用包里的配置文件，如下：
![image](https://cloud.githubusercontent.com/assets/15070379/18135630/214a2d94-6fd5-11e6-92e3-36d48f6f9b05.png)

目前我不知道是不是服务器上mysql安装的有问题，很奇怪，怎么都用不起来。

**Comment by lizheming** [comment]
那是试试直接命令行能登录 mysql 么

**Comment by bi-kai** [comment]
@lizheming 我的mysql版本是5.6.31，刚装了其他建站系统，数据表创建和发帖都是正常的，说明mysql没有问题。

nginx用的是你提供的默认配置，为什么static资源无法加载？

**Comment by bi-kai** [comment]
@lizheming nginx还需要添加什么规则么？

**Comment by lizheming** [comment]
给个地址我自己去看看吧

**Comment by bi-kai** [comment]
@lizheming 
http://scl.guzheng.org.cn/
mysql版本：`mysql-5.6.31-linux-glibc2.5-x86_64`
nginx版本：`1.10.1`
nginx配置：
```
server {
    listen 80;
    server_name scl.guzheng.org.cn;
    root /alidata/www/blog_firekylin;
    set $node_port 8360;

    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /Users/welefen/Develop/git/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
}
    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }


    location ~ /static/ {
        etag         on;
        expires      max;
    }
}

#http/2 nginx conf
...
```
别的文件均未改动，安装时，报本issues中截图的错误，不过数据表已经创建了。
页面显示的问题，有些资源无法加载上来，nginx规则有问题吧。
目录结构如下，你看少没少文件：
![image](https://cloud.githubusercontent.com/assets/15070379/18611463/7a276fea-7d6c-11e6-928d-543cd316bdb0.png)

**Comment by bi-kai** [comment]
@lizheming 你看上述描述还少什么信息不？如果需要到环境上定位，我可以把环境信息邮箱发给你。

**Comment by lizheming** [comment]
@bi-kai 你的 root 错了，应该是 

```
root /alidata/www/blog_firekylin/www;
```

**Comment by bi-kai** [comment]
@lizheming 添加www后，终于能正常使用了。但是后台日志 还是有些问题：
![image](https://cloud.githubusercontent.com/assets/15070379/18617146/9d0041ec-7dfb-11e6-9767-a77939863513.png)
虽然目前没看出有什么影响，但是报错总是让人不安。
数据库表是正常创建了的：
![image](https://cloud.githubusercontent.com/assets/15070379/18617139/84eddc9a-7dfb-11e6-9a85-ee2dc6393d43.png)

**Comment by lizheming** [comment]
错误信息我也看不出什么来，如果没发现什么问题就再说吧，只要数据还在库里就好。我先把这个 issue 关闭啦，之后有问题再开吧。
