### ISSUE TITLE
【求助】搭建博客后经常会出现访问time-out

### ISSUE THREAD

**Issue by iischajn** [75team/firekylin#149]
每当pm2监控后内存会逐渐升到50M之后，就几乎无法访问了。经常time-out。pm2重启项目后就好了…内存回到了10M。不知道大家有出现过这样的现象么？我该如何解决这个问题呢？

![image](https://cloud.githubusercontent.com/assets/3065129/18226480/74472fbe-723d-11e6-8f20-471ed151eb84.png)

BLOG:http://chajn.org/

**Comment by lizheming** [comment]
pm2 刚启动时内存占用小是正常的，我有间断性的访问你的博客，没有出现无法访问的情况（可能我正好没命中？issue 我先暂时关闭了，有问题可继续在此 issue 上评论。

**Comment by lizheming** [comment]
![image](https://cloud.githubusercontent.com/assets/424491/24071374/1e226c30-0c0b-11e7-85c4-9794524ee800.png)
附上我的博客 pm2 截图 =w=
