### ISSUE TITLE
admin页面空白

### ISSUE THREAD

**Issue by haodalong** [75team/firekylin#151]
你好，我在安装完成后访问admin页面遇到如下错误，还请指教，非常感谢

Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8360/static/js/admin.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8360/static/js/common.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8360/static/js/admin.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by haodalong** [comment]
问题已经解决，需要在控制台进行如下操作：

C:\Users\Desktopadmin\Desktop\code\nodejs\firekylin-master>npm run webpack

> Firekylin@0.12.7 webpack C:\Users\Desktopadmin\Desktop\code\nodejs\firekylin-m
aster
> webpack --watch

Hash: edca650059056dc35762
Version: webpack 1.13.2
Time: 13560ms
              Asset     Size  Chunks             Chunk Names
    admin.bundle.js  3.38 MB       0  [emitted]  admin
          common.js  2.01 MB       1  [emitted]  vendor
admin.bundle.js.map  4.05 MB       0  [emitted]  admin
      common.js.map  2.41 MB       1  [emitted]  vendor
   [0] multi vendor 124 bytes {1} [built]
    + 1505 hidden modules

**Comment by lizheming** [comment]
你是不是直接 clone 的仓库....

> 注：普通安装请直接按照下方操作说明使用安装包安装。仓库的是开发版不建议使用，如需安装开发版请参见 如何贡献代码。
> - via: [安装](https://github.com/75team/firekylin/blob/master/README.md#安装)
