### ISSUE TITLE
ec2在npm install之后无法使用npm start启动服务

### ISSUE THREAD

**Issue by haodalong** [75team/firekylin#152]
ec2在npm install之后无法使用npm start启动服务，报错如下：
npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/home/ec2-user/software/node-v4.4.5-linux-x64/bin/node" "/home/ec2-user/software/node-v4.4.5-linux-x64/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! Firekylin@0.12.7 start: `node www/development.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Firekylin@0.12.7 start script 'node www/development.js'.
npm ERR! This is most likely a problem with the Firekylin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node www/development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Firekylin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls Firekylin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/code/firekylin-master/npm-debug.log

恳请协助解决，谢谢

**Comment by lizheming** [comment]
https://github.com/75team/firekylin#安装
请按照安装过程来，下载 http://firekylin.org/release/latest.tar.gz 安装包，不要直接 clone

**Comment by haodalong** [comment]
好的，下载 http://firekylin.org/release/latest.tar.gz 安装包后可以成功编译和运行，谢谢，但是又遇到如下问题：https://github.com/75team/firekylin/issues/153
