### ISSUE TITLE
ec2上安装nginx并配置完成后，错误日志打印如下错误，求解

### ISSUE THREAD

**Issue by haodalong** [75team/firekylin#153]
各位大神好，我在配置 nginx的时候，由于文件/etc/nginx/nginx,conf的配置包含：
include /etc/nginx/conf.d/*.conf;

所以我直接在/etc/nginx/conf.d/文件夹下配置firekylin给出的nginx_default.conf，但配置完成后，在错误日志看到如下权限问题，还请协助解决，谢谢
2016/09/11 06:23:40 [crit] 17206#17206: *1 connect() to 127.0.0.1:3000 failed (13: Permission denied) while connecting to upstream, client: 180.152.106.185, server: www.xxx.pub, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "www.xxx.pub"

**Comment by lizheming** [comment]
贴下你的 nginx 配置吧

**Comment by haodalong** [comment]
/etc/nginx/conf.d/default.conf

server {
    listen       80;
    server_name  www.dalong.pub dalong.pub;
    #server_name  127.0.0.1

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    root /home/ec2-user/code/firekylin/www;
    set $node_port 3000;    
    index index.js index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
      alias /Users/welefen/Develop/git/firekylin/ssl/challenges/;
      try_files $uri = 404;
    }

    location / {
	proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

   location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }


    location ~ /static/ {
        etag         on;
        expires      max;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

**Comment by lizheming** [comment]
看配置没啥问题，你 Google 搜下吧，我在 Google 搜到一个和你类似的问题你可以参考一下：http://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

**Comment by haodalong** [comment]
好的，问题解决，最简单的处理方法，将SELinux 关闭

检查SELinux有没在运行

# getenforce

直接关闭SELinux，重启失效

# setenforce Permissive
