### ISSUE TITLE
怎样在首页显示文章摘要而不是全文

### ISSUE THREAD

**Issue by haodalong** [75team/firekylin#154]
各位大神，你们好，中秋快乐。

请问如何在首页只显示文章摘要，而不是显示全文，需要怎么配置或者修改哪些代码？另外，用户角色为编辑的时候也不允许上传本地图片，这个控制在哪里修改，请指教，谢谢

**Comment by qgy18** [comment]
在你的文章中插入`<!--more-->` 该标签之前的即为文章摘要

**Comment by haodalong** [comment]
好的，非常感谢，第一个问题解决。
