### ISSUE TITLE
发布文章字符问题

### ISSUE THREAD

**Issue by fegg** [75team/firekylin#155]
比如 '𝌆' 字符。
在后台 markdown 编辑后，保存草稿或者发布后，都将丢失这类字符之后的文字。

**Comment by fegg** [comment]
好像是 mysql 不支持的问题，先关闭。

**Comment by qgy18** [comment]
编码搞成 utf8mb4 啊

**Comment by fegg** [comment]
@qgy18 嗯嗯，就是搞成 utf8mb4 了～还有点小问题，这周末再搞了，有问号，应该是编码没对上，不过能存储了。
