### ISSUE TITLE
升级

### ISSUE THREAD

**Issue by beyourhero** [75team/firekylin#157]
升级后左侧的首页归档等都不见了  从0.12-0.18

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/wiki/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7#0123---0124

需要更新下数据库，值参考 https://github.com/75team/firekylin/blob/master/db/firekylin.sql#L75

```
INSERT INTO `fk_options` (`key`, `value`, `desc`)
VALUES
('navigation', '[{"label":"首页","url":"/","option":"home"},{"label":"归档","url":"/archives/","option":"archive"},{"label":"标签","url":"/tags","option":"tags"},{"label":"关于","url":"/about","option":"user"},{"label":"友链","url":"/links","option":"link"}]', '导航菜单');
```

**Comment by beyourhero** [comment]
![qq 20161009171356](https://cloud.githubusercontent.com/assets/12791216/19219364/cc168722-8e43-11e6-92a4-7a1645546677.png)
依然无效

**Comment by lizheming** [comment]
需要重启服务

**Comment by beyourhero** [comment]
重启了

**Comment by beyourhero** [comment]
好了额

**Comment by lizheming** [comment]
好的~

**Comment by Jerret321** [comment]
升级之后 一直 让install
