### ISSUE TITLE
关于菜单属性

### ISSUE THREAD

**Issue by aalj** [75team/firekylin#160]
在设置菜单属性的时候，不能发现默认列表。对于新人来说要去设置这个菜单属性显示图标，存在一定的难度

**Comment by lizheming** [comment]
你好，请问不能发现默认列表是什么意思？菜单属性默认的主题是用来显示图标的，但是你也可以用来干更复杂的事情，具体可以看 https://github.com/75team/firekylin#常见问题 常见问题的答疑。

**Comment by aalj** [comment]
情形是这样的：在我搭建好整个blog（v12.7）以后发现在管理页面-->外观设置-->菜单管理里面新建菜单以后，在主页上对应的标签并没有相应的显示图标。如果有可能应该在新建菜单的时候能够设置图标，这样对于新手来说可以减少入门的门槛

**Comment by lizheming** [comment]
这个不太好支持，因为图标是和主题强相关的，只是现在默认主题是有图标的然后属性是用做图标显示了，但是换了个别的主题之后就不一定有图标了，属性可能就用来干别的了。暂时还想不到很好的方法保证高耦合又足够友好，所以就这样了。
