### ISSUE TITLE
为什么/admin页面打开奇慢无比

### ISSUE THREAD

**Issue by fanqi** [75team/firekylin#161]
在chrome的network中竟然有个1.8M的admin.bundle.js

**Comment by lizheming** [comment]
嗯，目前没经过压缩，所以有点大，我下个版本处理下吧 =w= 感谢反馈~

**Comment by lizheming** [comment]
fixed https://github.com/75team/firekylin/commit/c45591872746f88a0d5528667477f7a9808b0e32
