### ISSUE TITLE
自 0.12.7 开始文章列表无法加载

### ISSUE THREAD

**Issue by StevenGuanYZ** [75team/firekylin#164]
打开文章列表显示 “加载中……” ，就是一直加载不出来。
除了这个页面之外其他功能一切正常，比如编辑系统设置都能正常的加载和保存，应该和 MySQL 的连接上是没有问题的，也能发布新文章和新增草稿，唯独是加载不出来文章列表。

**Comment by lizheming** [comment]
看看控制台报什么错了？我这看着是没有问题的。

**Comment by StevenGuanYZ** [comment]
具体是哪里的控制台呢？

Chrome 看到有五个叹号和五个错误：

require('rc-util') is deprecated, please require('rc-util/lib/xx')
admin.bundle.js?v=c132f:10 `rcUtil classSet` is deprecated, use `classNames()` by `require('classnames')` instead
admin.bundle.js?v=c132f:10 `rcUtil joinClasses()` is deprecated, use `classNames()` by `require('classnames')` instead
admin.bundle.js?v=c132f:10 `rcUtil PureRenderMixin` is deprecated, use `react-addons-pure-render-mixin` by `require('react-addons-pure-render-mixin')` instead
admin.bundle.js?v=c132f:7 Uncaught (in promise) TypeError: Cannot read property 'display_name' of undefined(…)(anonymous function) @ admin.bundle.js?v=c132f:7t.getPostList @ admin.bundle.js?v=c132f:7t.render @ admin.bundle.js?v=c132f:7_renderValidatedComponentWithoutOwnerOrContext @ common.js?v=c277c:16_renderValidatedComponent @ common.js?v=c277c:16ReactCompositeComponent__renderValidatedComponent @ common.js?v=c277c:1_updateRenderedComponent @ common.js?v=c277c:16_performComponentUpdate @ common.js?v=c277c:16updateComponent @ common.js?v=c277c:16ReactCompositeComponent_updateComponent @ common.js?v=c277c:1performUpdateIfNecessary @ common.js?v=c277c:16performUpdateIfNecessary @ common.js?v=c277c:16s @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16L @ common.js?v=c277c:16ReactUpdates_flushBatchedUpdates @ common.js?v=c277c:1closeAll @ common.js?v=c277c:16perform @ common.js?v=c277c:16batchedUpdates @ common.js?v=c277c:17u @ common.js?v=c277c:16r @ common.js?v=c277c:16enqueueSetState @ common.js?v=c277c:16r.setState @ common.js?v=c277c:19t.handleTrigger @ admin.bundle.js?v=c132f:7n @ admin.bundle.js?v=c132f:5i.emit @ admin.bundle.js?v=c132f:5trigger @ admin.bundle.js?v=c132f:5(anonymous function) @ admin.bundle.js?v=c132f:7
admin.bundle.js?v=c132f:16 Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message
admin.bundle.js?v=c132f:7 Uncaught (in promise) TypeError: Cannot read property 'display_name' of undefined(…)(anonymous function) @ admin.bundle.js?v=c132f:7t.getPostList @ admin.bundle.js?v=c132f:7t.render @ admin.bundle.js?v=c132f:7_renderValidatedComponentWithoutOwnerOrContext @ common.js?v=c277c:16_renderValidatedComponent @ common.js?v=c277c:16ReactCompositeComponent__renderValidatedComponent @ common.js?v=c277c:1_updateRenderedComponent @ common.js?v=c277c:16_performComponentUpdate @ common.js?v=c277c:16updateComponent @ common.js?v=c277c:16ReactCompositeComponent_updateComponent @ common.js?v=c277c:1performUpdateIfNecessary @ common.js?v=c277c:16performUpdateIfNecessary @ common.js?v=c277c:16s @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16L @ common.js?v=c277c:16ReactUpdates_flushBatchedUpdates @ common.js?v=c277c:1closeAll @ common.js?v=c277c:16perform @ common.js?v=c277c:16batchedUpdates @ common.js?v=c277c:17u @ common.js?v=c277c:16r @ common.js?v=c277c:16enqueueSetState @ common.js?v=c277c:16r.setState @ common.js?v=c277c:19t.handleTrigger @ admin.bundle.js?v=c132f:7n @ admin.bundle.js?v=c132f:5i.emit @ admin.bundle.js?v=c132f:5trigger @ admin.bundle.js?v=c132f:5(anonymous function) @ admin.bundle.js?v=c132f:7
admin.bundle.js?v=c132f:7 Uncaught (in promise) TypeError: Cannot read property 'display_name' of undefined(…)(anonymous function) @ admin.bundle.js?v=c132f:7t.getPostList @ admin.bundle.js?v=c132f:7t.render @ admin.bundle.js?v=c132f:7_renderValidatedComponentWithoutOwnerOrContext @ common.js?v=c277c:16_renderValidatedComponent @ common.js?v=c277c:16ReactCompositeComponent__renderValidatedComponent @ common.js?v=c277c:1_updateRenderedComponent @ common.js?v=c277c:16_performComponentUpdate @ common.js?v=c277c:16updateComponent @ common.js?v=c277c:16ReactCompositeComponent_updateComponent @ common.js?v=c277c:1performUpdateIfNecessary @ common.js?v=c277c:16performUpdateIfNecessary @ common.js?v=c277c:16s @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16perform @ common.js?v=c277c:16L @ common.js?v=c277c:16ReactUpdates_flushBatchedUpdates @ common.js?v=c277c:1closeAll @ common.js?v=c277c:16perform @ common.js?v=c277c:16batchedUpdates @ common.js?v=c277c:17u @ common.js?v=c277c:16r @ common.js?v=c277c:16enqueueSetState @ common.js?v=c277c:16r.setState @ common.js?v=c277c:19t.handleTrigger @ admin.bundle.js?v=c132f:7n @ admin.bundle.js?v=c132f:5i.emit @ admin.bundle.js?v=c132f:5trigger @ admin.bundle.js?v=c132f:5(anonymous function) @ admin.bundle.js?v=c132f:7
admin.bundle.js?v=c132f:6 GET https://g.32ph.com/admin/api/system?_r=0.41322704339392935 504 ()f.end @ admin.bundle.js?v=c132f:6request @ admin.bundle.js?v=c132f:6onSelect @ admin.bundle.js?v=c132f:7n @ admin.bundle.js?v=c132f:5i.emit @ admin.bundle.js?v=c132f:5trigger @ admin.bundle.js?v=c132f:5(anonymous function) @ admin.bundle.js?v=c132f:5
admin.bundle.js?v=c132f:5 Uncaught (in promise) Error: Unsuccessful HTTP response(…)(anonymous function) @ admin.bundle.js?v=c132f:5r.emit @ admin.bundle.js?v=c132f:6n.onreadystatechange @ admin.bundle.js?v=c132f:6

**Comment by lizheming** [comment]
这输出看着也没错呀…

**Comment by StevenGuanYZ** [comment]
那有什么方法可以看到网站内部的错误吗？

**Comment by lizheming** [comment]
后台应该是没错的，你给一个你的账号给我吧，我去试一下，i@imnerd.org

**Comment by lizheming** [comment]
![image](https://cloud.githubusercontent.com/assets/424491/19615604/2c35d64a-9834-11e6-94b4-2aa95d4d272a.png)
我去后台看了下，可以看到列表呀。数据库读取方式没有变，最近几个版本都是一些 bug fix，如果改了这个肯定都是要发大版本的。

**Comment by StevenGuanYZ** [comment]
我的天 ……… 现在真的可以了。你并没有改动过什么吗？ 😂😂😂😂

**Comment by lizheming** [comment]
什么也没动啊。。。。。我就跑上去看了下。。。。发现就是可以的。。。=。=||

**Comment by StevenGuanYZ** [comment]
好奇怪 … 我给账户你之前试过不行的。然后也用了新建给你的账户登入过也是只显示加载中 ……，现在好了就行 😂 谢谢你！

**Comment by lizheming** [comment]
这个，可能是。。。。看脸？![摊手](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/09/pcmoren_tanshou_org.png)
