### ISSUE TITLE
自定义footer

### ISSUE THREAD

**Issue by hysg** [75team/firekylin#165]
怎么自定义footer？我想添加一个又拍云的链接和logo。

**Comment by lizheming** [comment]
自定义 footer 需要修改主题文件，默认主题再 `www/theme/firekylin/layout.html` 该文件中。

不过不建议直接修改默认主题，在升级的时候很可能会被覆盖掉，建议拷贝 `www/theme/firekylin` 默认主题为一份新的主题例如 `www/theme/firekylin-modified` 同时修改 `www/theme/firekylin-modified/package.json` 中的 `name` 属性，完成一份自定义主题的制作。之后在后台外观设置-主题管理中选择自己的自定义主题，然后重启pm2服务即可切换默认主题为自己的自定义主题。

之后修改自定义主题的 `www/theme/firekylin-modified/layout.html` 文件为你想要的内容，就不会在升级的时候被覆盖掉啦。
