### ISSUE TITLE
首页的文章列表怎么只显示部分内容

### ISSUE THREAD

**Issue by chenxiaoshan** [75team/firekylin#166]
首页的一大拉的文章列表，怎么只显示部分内容呀？我这边都是每篇文章都全部显示出来了，都没有隐藏内容。

**Comment by lizheming** [comment]
> **文章如何设置摘要？**
> 在你的文章中插入` <!--more-->` 该标签之前的即为文章摘要
>
> see more: https://github.com/75team/firekylin#常见问题

**Comment by chenxiaoshan** [comment]
谢谢谢谢！！！

**Comment by lizheming** [comment]
另外编辑器的最后一个图标是可以快捷输入 `<!--more-->` 标签的~
