### ISSUE TITLE
访问admin后台时 admin.bundle.js 和 common.js 加载很慢

### ISSUE THREAD

**Issue by HarlanZhang** [75team/firekylin#171]
firekylin\www\static\js 下的 admin.bundle.js 和 common.js 为啥在国内服务器上加载速度慢呢 。。。
同样的项目我安装在美国服务器上，在国内访问2秒多。 安装在国内服务器后则需要20~30秒才能加载完毕。本宝宝不动代码，只是想搭建个博客玩玩，求解

**Comment by lizheming** [comment]
这两个包比较大，之前有人反馈过，下个版本我们会把包变小一点。

**Comment by lizheming** [comment]
已经做了优化，首次后台加载已经减小到 800KB 左右了，等下一个版本发版吧~😋

**Comment by HarlanZhang** [comment]
今天升级了0.13.0版本，admin后台打开确实比之前快了不少，但依然还是比较慢，延迟在5~8秒左右，这个感觉还是不正常... @lizheming 
[我的博客](https://yaahuan.com/admin) 可以看一下。

**Comment by lizheming** [comment]
你是不是没有用我们自带的 nginx 配置文件呀？我看你的静态文件一直都没有被缓存，文件缓存的话后台的打开效果应该会秒开。这个版本优化效果比较明显，我后期再看看，能不能减小一下 common.js 的体积。

**Comment by HarlanZhang** [comment]
嗯， 我检查了一下nginx配置，确实有问题，重新配置了一下，第一次加载还是如上所说，需要5~8秒，缓存后正常， 我找了一些其他用firekylin的博客，第一次也很快，囧~~
