### ISSUE TITLE
怎么给文章加目录的？

### ISSUE THREAD

**Issue by weixiaokang** [75team/firekylin#172]
我看到奇舞团的博客中有目录，点击之后能调到对应标题的正文。这是支持[TOC]吗？

**Comment by lizheming** [comment]
是的，不需要写 `[TOC]`，只要用 `#`, `##`, `###` 之类的N级标题写的话程序会自动识别给加上目录的。

**Comment by Jerret321** [comment]
这个目录怎么弄的~ 一直用的老版本 新版本自动支持吗？ 需要怎么迁移和设置 @lizheming

**Comment by lizheming** [comment]
@Jerret321 一直都有，文章有 ##, ### 的 N 级标题就好了
