### ISSUE TITLE
主机重启之后启动出现问题

### ISSUE THREAD

**Issue by lee3164** [75team/firekylin#174]
我有次重启了主机,然后重新用pm2启动博客系统,但是却又重新进入了那个最开始的界面,就是那个输入用户名,密码,数据库重新让你创建一个博客的界面,怎么回事?

**Comment by lizheming** [comment]
根目录下看看有没有 `.installed` 文件？

**Comment by lee3164** [comment]
有啊,求教怎么解决,

**Comment by lizheming** [comment]
有就不会的，没有这个文件才会跳到创建页面。

**Comment by lee3164** [comment]
但是确跳到了创建界面,.installed文件里面什么都没有啊.

**Comment by lee3164** [comment]
????????我也不知怎么回事啊

**Comment by lizheming** [comment]
`.installed` 文件就是一个空文件，不需要内容的。我看代码没啥问题，难道是你的文件权限问题，node 没法读取？

**Comment by lee3164** [comment]
搞定了,我用sudo启动pm2就可以了,但是我的那个.installed是777的权限,之前应该也可以访问啊.

**Comment by lizheming** [comment]
额，你直接 `node www/production.js` 启动试试看是什么效果？
