### ISSUE TITLE
前后端完全分离的吗？想用vue改一下

### ISSUE THREAD

**Issue by wjkang** [75team/firekylin#176]

**Comment by lizheming** [comment]
管理后台是前后端分离的，前端页面的话我们支持自定义主题，你可以改造下把原来的所有页面改成输出接口数据，自己写一个单页用来做博客主页，这个还是非常简单的。

**Comment by Smallpath** [comment]
哈哈,  我已经做了这件事了, 并且弄了服务端渲染.  [这里](https://smallpath.me/post/thinkjs-ssr)有我写的一篇博文, 是关于vue2服务端渲染和Thinkjs搭配的, 有兴趣可以看一看

**Comment by lizheming** [comment]
@Smallpath 给你32个赞~哈哈，不过你是不是说的管理后台？我看前台好像还是 ThinkJS 的模板。

**Comment by wjkang** [comment]
@lizheming 他是用VUE重写了一样的界面

**Comment by lizheming** [comment]
@wjkang 这样啊...也是厉害，哈哈！

**Comment by Smallpath** [comment]
@lizheming 主题还是火麒麟的，之后准备把屈屈那样的侧边栏图片也给加上，我搭这个就是为了追赶屈屈的首屏加载速度，哈哈

**Comment by qgy18** [comment]
@Smallpath 你的博客速度非常快！

**Comment by Smallpath** [comment]
@qgy18 谢谢屈屈, 我的博客服务器上的nginx基本都是按照你的文章优化的, 非常喜欢你的文章!
