### ISSUE TITLE
评论统计数量不更新

### ISSUE THREAD

**Issue by MrLiuDev** [75team/firekylin#177]
请问评论后显示评论数依然为0是什么原因？数据库中comment_num字段为0

**Comment by lizheming** [comment]
国内主机+Disqus么？Disqus在国内访问有问题的，可以换成多说试试~

**Comment by MrLiuDev** [comment]
@lizheming 国外vps+多说，查看数据库确实comment_num没有得到更新

**Comment by lizheming** [comment]
那难道多说的接口抽了？你用 `npm start` 的方式启动下看看后台的 log 请求多说接口有没有成功。

**Comment by MrLiuDev** [comment]
@lizheming 查看后台也没有请求接口失败的信息。把博客服务端重启后评论统计数量就更新了，但是在运行过程中有新添加评论却不能实时更新，只有重启博客程序才会更新。

**Comment by lizheming** [comment]
那就是 crontab 没运行成功了，我们是启动的时候调 node-crontab 添加计划任务定时拖数据的，稍后我再瞅瞅。

**Comment by MrLiuDev** [comment]
好的😁

**Comment by MrLiuDev** [comment]
刚看到更新支持了七牛云和upyun，这个功能还是比较需要的。火麒麟最近有更新的计划吗？

**Comment by lizheming** [comment]
有的，今天因为服务器挂了没发，OK的话可能明天就会发一版，静待后台的更新提示吧~😋
