### ISSUE TITLE
firekylin.sql 中sql语句异常导致安装失败

### ISSUE THREAD

**Issue by CCcle** [75team/firekylin#181]
INSERT INTO `fk_options` (`key`, `value`, `desc`)
VALUES
  ('analyze_code','','统计代码，可以添加百度统计、Google 统计等'),
  ('comment','{\"type\":\"duoshuo\",\"name\":\"welefen2013\"}','评论类型'),
  ('description','A Simple & Fast Node Bloging Platform Base On ThinkJS 2.0 & ReactJS & ES6/7','网站描述'),
  ('favicon_url','','favicon'),
  ('github_blog','welefen/blog','GitHub blog 地址，如果填了则同步到 GitHub 上'),
  ('github_url','https://github.com/75team/thinkjs','GitHub 地址'),
  ('image_upload',NULL,'图片存放的位置，默认存在放网站上。也可以选择放在七牛或者又拍云等地方'),
  ('keywords','www,fasdf,fasdfa','网站关键字'),
  ('logo_url','/static/img/firekylin.jpg','logo 地址'),
  ('miitbeian','wewww','网站备案号'),
  ('num_per_page','10','文章一页显示的条数'),
  ('password_salt','firekylin','密码 salt，网站安装的时候随机生成一个'),
  ('push','0','是否允许推送'),
  ('push_sites','','推送网站列表'),
  ('site_url','http://127.0.0.1:8360','网站地址'),
  ('theme','firekylin','主题名称'),
  ('title','Firekylin 系统','网站标题'),
  ('twitter_url','','微博地址'),
  ('navigation', '[{"label":"首页","url":"/","option":"home"},{"label":"归档","url":"/archives/","option":"archive"},{"label":"标签","url":"/tags","option":"tags"},{"label":"关于","url":"/about","option":"user"},{"label":"友链","url":"/links","option":"link"}]', '导航菜单'),
  ('two_factor_auth','','是否开启二步验证')
  ('upload',NULL,'上传配置，默认为本地，也可以选择七牛或者又拍云');

最后两句sql里面少一个','号，导致sql运行异常，应用安装失败

**Comment by lizheming** [comment]
@excaliburhan →_→ 收到了，我们火速更新一下。

**Comment by excaliburhan** [comment]
😅尴尬

**Comment by CCcle** [comment]
直接下载压缩包支持安装吗？还是一定要用tar.gz安装？直接下zip来安装 
case 7:
              dbFile = think.ROOT_PATH + think.sep + 'firekylin.sql';

这里会出问题  因为sql好像是放在db里面了，会提示找不到文件 有点尴尬

**Comment by lizheming** [comment]
用 tar.gz 的吧，https://github.com/75team/firekylin#安装 按照说明文件来就好了~ 仓库的是开发版需要自己导数据库的，你直接按照安装说明的步骤来吧。

**Comment by CCcle** [comment]
恩 我自己安装时没问题  我自己能改改 主要是前几天75那边不能访问 tar.gz 也不能下载 我就用仓库clone了 然后就没安装上......

**Comment by lizheming** [comment]
嗯，前两天官网主机有点问题，昨天已经弄好了，之后我会在 release 也补充放一份，抱歉啦。

**Comment by CCcle** [comment]
然后今天又不能访问了..........坑爹啊

**Comment by lizheming** [comment]
http://firekylin.org/release/ 没问题的，别看首页... 首页还么弄...

**Comment by CCcle** [comment]
你别骗我

**Comment by lizheming** [comment]
你不行？我这真的是好的。。。。你 ping 下 IP ？

**Comment by excaliburhan** [comment]
我这稳定50ms以内（逃

**Comment by CCcle** [comment]
ping 得同 访问不了 ...尴尬

**Comment by lizheming** [comment]
你再试试

**Comment by bpplpp** [comment]
怎么从数据库关闭两步验证？昨 IOS 清理刷机，Duo 进去后需要验证，咋办？

**Comment by lizheming** [comment]
@bpplpp
 
```sql
DELETE FROM `fk_options` WHERE `name` = 'two_factor_auth';
```

把 two_factor_auth 这个删掉就好了。
