### ISSUE TITLE
请教正确的更新姿势

### ISSUE THREAD

**Issue by MrLiuDev** [75team/firekylin#183]
今天更新0.13.0版本，把旧版本文件删除后，把新版本文件复制过去，重新启动服务却发现访问时出现500。可能是我的更新方式不对，删除掉了不该删的东西。只好重装了，还好安装很方便。
请问更新是把新版本文件直接复制覆盖旧版本的文件吗？直接删除或许会删除掉不该删除的东西。
或许以后可以在后台添加一个更新的功能，就更加方便了。O(∩_∩)O

**Comment by lizheming** [comment]
其实更新非常简单... 执行以下几个命令就可以了，假设你的文件夹在 `/home/liudev/blog`。

```
wget http://firekylin.org/release/latest.tar.gz
tar zvxf latest.tar.gz
cp -r firekylin/* /home/liudev/blog
cd /home/liudev/blog
npm install
pm2 restart pm2.json
```

基本上就是下载最新版解压覆盖文件安装新增依赖重启 pm2 就可以了，我一下子能更新一打博客→_→ 而且 `lastest.tar.gz` 这个文件夹永远指向最新版，所以更新最新版都可以写一个脚本搞定~ 没有添加自动更新的功能是因为最后 pm2 的重启有可能其它人用的是其它的进程守护工具不太确定所以还在想怎么比较好的兼容大家的情况。我稍后把如何更新加到常见问题里吧，这样大家也能稍微明白点~ 自动更新我一直在考虑怎么加，如果有想法我会加上的。

**Comment by lizheming** [comment]
0.14.0 后已在后台增加了在线更新的功能，欢迎试用~
