### ISSUE TITLE
配置七牛云后上传图片报转错

### ISSUE THREAD

**Issue by HarlanZhang** [75team/firekylin#184]
配置七牛云后上传图片一直不成功，控制台报如下错误，是json转换有问题吗?

Google 浏览器
`Uncaught SyntaxError: Unexpected token < in JSON at position 0`
   ` at JSON.parse (<anonymous>)`
   ` at XMLHttpRequest.i.onload (https://yaahuan.com/static/js/admin.js?v=8ee5c:6:8883)`
`i.onload @admin.js?v=8ee5c:6`

火狐浏览器
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
`admin.js:6:8878`
`y.upload/</i.onload`

**Comment by lizheming** [comment]
@excaliburhan 麻烦跟进一下这个 issue 谢谢~

**Comment by excaliburhan** [comment]
好的，我看一下

**Comment by excaliburhan** [comment]
@lizheming @HarlanZhang 

原因找到了，是0.13.0版本upyun依赖问题，依赖写到devDependencies里了，打线上版本就忽略了这个module。

@HarlanZhang 你的项目可以直接npm install upyun --save，重启服务应该就可以解决
麻烦 @lizheming 重新发布一个0.13.0的版本

**Comment by lizheming** [comment]
又拍云？不是七牛么？

**Comment by excaliburhan** [comment]
是因为模块依赖少了，导致上传都会报错的，后台直接报500啦

**Comment by lizheming** [comment]
唔？这样啊... 我怎么记得我用的时候好好的呢 =_=||| 这个我稍后发一个 0.13.1 版本出来吧，bug 还是要强制 0.13 的人全部升级的。

**Comment by excaliburhan** [comment]
对的，需要发一个版本强制升级。

自己没错的原因也简单，因为自己用的时候基本是开发代码跑webpack的，会有dev的依赖。
我下载0.13.0版本本地测试过了，还要安装upyun依赖就ok了，你也可以再测下。

**Comment by lizheming** [comment]
0.13.1 版已发布，@HarlanZhang 可以试试还有问题没。

**Comment by HarlanZhang** [comment]
@lizheming 已经验证，现在没有问题了，感谢！
