### ISSUE TITLE
后台本地上传logo图片没有成功

### ISSUE THREAD

**Issue by sanrudongfeng** [75team/firekylin#188]
0.13.0这个版本，
1.后台管理系统上传logo图片时数据库里面的suffix__options里面的image_upload字段为空，
2.根据猜想静态图片应该是上传以后放到这个位置项目下面的www/static/img下，在项目下面的www/static/img下面也没有找到图片，只有默认的几张图片；
3.后台管理系统提交基本设置，发起的请求 exapmle.com/admin/options/general报json解析错误。
4.http://exapmle.com/static/js/admin.js?v=8ee5c:6:8883这个文件json解析错误；
5.上传不成功也可能不是这个原因。

主要不是搞前端的，，，这个react也不会啊，，，要不就自己动手解决，不来麻烦各位了，谢谢，求帮忙解决。

**Comment by lizheming** [comment]
介意提供一个测试账号么，我的邮箱 i@imnerd.org

**Comment by sanrudongfeng** [comment]
@lizheming 已发邮箱

**Comment by lizheming** [comment]
收到，我去看看

**Comment by lizheming** [comment]
你的博客也没有设置缓存呢，每次刷页面都要重新获取一下静态资源，按照官方的配置设置下缓存吧。

**Comment by lizheming** [comment]
居然是在家里搭的，厉害了word哥！

**Comment by lizheming** [comment]
额，我知道啦，你升一下 0.13.1 吧，0.13 有个小 BUG导致上传有问题，0.13.1 修复了你试试。

**Comment by sanrudongfeng** [comment]
@lizheming ，已解决，very very thanks。

**Comment by lizheming** [comment]
应该是我说抱歉才是，发版有问题给你带来困扰了真是抱歉 ~
