### ISSUE TITLE
请问firekylin中用的是什么markdown编辑器呢？

### ISSUE THREAD

**Issue by fanqi** [75team/firekylin#189]
请问firekylin中用的是什么markdown编辑器呢？

**Comment by lizheming** [comment]
是基于 https://github.com/leozdgao/react-markdown 这个项目然后自己改造的，之前也是找了很久相关的编辑器，因为一直喜欢 SF 家的样式所以对这个项目格外的有好感，好在代码也不复杂自己修改一下也 OK。之前比较仓促也没有在代码中附上相关的说明，前两天还念叨这事要翻一下把作者的 repo 注释在文件里，一直忙也忘记了，正好借你这个 issue 又回去找了下，谢谢~

**Comment by fanqi** [comment]
谢谢，我想在最近的项目中集成markdown，找了一圈还是觉得我们firekylin的编辑器好用，去下来试试

**Comment by lizheming** [comment]
嗯，可以下下来自己改造一下，或者直接用 Firekylin 的编辑器就好了，最近我也有想法想要把编辑器解耦出来，看之后有什么新的 idea 吧~
