### ISSUE TITLE
后台管理系统使用问题

### ISSUE THREAD

**Issue by sanrudongfeng** [75team/firekylin#192]
在使用后台管理系统时，比如添加菜单设置，菜单样式不知道如何添加（看其它人的博客添加的类名，碰巧对了）。
能否添加一个使用说明文档，有的地方对应起来还是不明显啊。

**Comment by lizheming** [comment]
默认主题自带的只有一些必须的图标，具体可以看样式文件：https://github.com/75team/firekylin/blob/master/www/theme/firekylin/res/css/icon.css 如果需要更多的图标的话可以上 iconfont.cn 上自行挑选，在主题自定义 CSS 中将图标样式添加进去之后即可使用。
