### ISSUE TITLE
为什么我申请来的证书是crt后缀，而nginx.conf里示例是pem格式？

### ISSUE THREAD

**Issue by cos800** [75team/firekylin#193]
如何配置https，求一份完整的说明文档。

**Comment by cos800** [comment]
我之前开发的PHP网站，是按照腾讯云的说明文档配置的，
https://www.qcloud.com/document/product/400/4143#2.-nginx.E8.AF.81.E4.B9.A6.E9.83.A8.E7.BD.B2

可是node这样子配置却不行。。。

**Comment by lizheming** [comment]
https://www.w3ctech.com/topic/1872 腾讯云可以参考这篇教程

**Comment by cos800** [comment]
嗯，我又重新配置了一篇 很神奇的又可以了…… 谢谢

**Comment by cos800** [comment]
发现是因为 我用了百度云加速的原因，关闭云加速就可以了。。。
