### ISSUE TITLE
感觉好多标点符号都打错了~编译有错~

### ISSUE THREAD

**Issue by hawskpy** [75team/firekylin#2]
gulp.watch(`${webDist}/*.{css,js}`, reload);
感觉好多标点符号都打错了~运行不了~还是我打开方式不对~

**Comment by songguangyu** [comment]
能否把报错的信息贴上 以便帮助你解决问题

**Comment by songguangyu** [comment]
aaa

**Comment by jedmeng** [comment]
gulpfile.babel.js使用ES2015语法，编译前请确认安装了babel-core模块
