### ISSUE TITLE
只有管理员才能修改密码吗？

### ISSUE THREAD

**Issue by finderL** [75team/firekylin#200]
只有管理员才能修改密码吗？

**Comment by lizheming** [comment]
额。。。刚去确认了下是个 BUG，平常都是管理员就没注意这个问题了。。。。我抽空修一下，感谢。。。。

**Comment by lizheming** [comment]
0.14.2 版已 fix 这个问题了，不过需要注意一下修改密码的入口在右上角用户名处。
