### ISSUE TITLE
希望添加正文关闭TOC功能

### ISSUE THREAD

**Issue by excaliburhan** [75team/firekylin#202]
1. 文章的正文如果不需要TOC，可以设置取消，目前找不到设置...
2. 正文如果有TOC，第一个h3标签会缺失（个人习惯使用h3标签做标题）

**Comment by lizheming** [comment]
第二个问题确认是 marked-toc 模块的问题，已经替换成 markdown-toc 了，效果好评。toc 取消这个暂时不加了，后期在阅读设置里增加一个选项让用户选择是否自动增加 TOC 目录，默认是，如果用户取消的话当用户在内容中添加 `<!-- toc -->` 或者 `[toc]` 也可以强制开启。目前如果想取消掉的话可以自定义 CSS
`.toc {display: none}`。

**Comment by excaliburhan** [comment]
好评！感觉toc和摘要的做成差不多的会比较好。
另外一个意见，希望以后可以维护一个版本更新的内容，现在看新功能都是看commit的，还是不够直观
比如用wiki？

**Comment by lizheming** [comment]
对，我想用 `<!-- toc -->` 这个，但是好像业界 `[toc]` 这种写法比较通用，也是满纠结。版本更新看 [CHANGELOG](https://github.com/75team/firekylin/blob/master/CHANGELOG.md) 吧

**Comment by excaliburhan** [comment]
可以可以，没注意到这个md

**Comment by lizheming** [comment]
在后台的更新提示里也会有这个更新日志的链接的，可以方便查看当前版本的更新内容

**Comment by excaliburhan** [comment]
那也只是更新的时候会看到，如果概况里有个永久链接会不会好点？一点意见，哈哈。

toc这个问题，其实marked中可以支持的就没有toc吧，都是各个编辑器自己定义的。大概看别人都是用`[toc]`，现在变一种共识了吧。

如果考虑别人的迁移或者编辑需求的话（比如用markdown编辑器编辑好再发布到博客），那还是用通用的比较好吧。

**Comment by lizheming** [comment]
其它情况需要看这个的概率应该不大，真的需要的话就到官方仓库来看吧。TOC 这个我再纠结下，个人比较倾向于 `<!-- toc -->`，保证内部操作的一致性才是最重要的。

**Comment by excaliburhan** [comment]
只要做到编辑器里面都不是问题～

手动输入很累滴

**Comment by lizheming** [comment]
这个不做编辑器快捷键了。
