### ISSUE TITLE
博客迁移

### ISSUE THREAD

**Issue by libenfu** [75team/firekylin#206]
我是从wordpress 迁移过来的 wordpress 上有700篇文章 我想了解下如何能做到数据迁移
后台导入wordpress.xml 无效呀
请问会有哪些问题存在不能成功导入

**Comment by lizheming** [comment]
介意把你的 wordpress.xml 发一份给我么，我看下是什么原因导致导入无效的，我的邮箱是 i@imnerd.org

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/commit/a184fbf34c0dcd8e06c2ae837c124a7afce97064 已经修复，好像是一个手误的问题[忧桑]... 等待下次发版吧
