### ISSUE TITLE
新安装，第一次npm start后无法登录后台，第二次npm start

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#213]

**Comment by choicky** [comment]
第二次 npm start 才能登录后台

第一次npm start后总是提示用户名或密码错误。我还以为我记错密码了。就重装，结果依然用户名或密码错误。

后来第二次 npm start后才能登录。现象与
https://github.com/75team/firekylin/issues/196
 完全相同

**Comment by lizheming** [comment]
使用 production.js 启动没这个问题，最新版已经修复了。
