### ISSUE TITLE
安装找不到数据库文件

### ISSUE THREAD

**Issue by alawnchen** [75team/firekylin#215]
启动了应用之后，打开了应用，跳到了安装配置页面，安装时候，却提示找不到相应的数据库文件！
![jietu20170115-140059](https://cloud.githubusercontent.com/assets/1811463/21960538/2458f4a4-db2b-11e6-9cd4-87f6eb13ef04.jpg)
我看了一下var rootPath = path.dirname(__dirname)是这样的，对应的service文件里面的数据库文件路径却是let dbFile = think.ROOT_PATH + think.sep + 'firekylin.sql';。对应的目录确实没有相应的文件，请更正一下代码！

**Comment by lizheming** [comment]
> 注：普通安装请直接按照下方操作说明使用安装包安装。仓库的是开发版不建议使用，如需安装开发版请参见 如何贡献代码。
> https://github.com/75team/firekylin#安装

**Comment by alawnchen** [comment]
@lizheming 囧，没注意到release版本，不好意思！
