### ISSUE TITLE
统计功能

### ISSUE THREAD

**Issue by blackfader** [75team/firekylin#218]
如果博客是一个团队在写，能有个统计功能是极好的。
* 统计每个成员的贡献量
* 统计总体文章数量，基于时间的柱状图等
* 统计出阅读数量，评论数量（当然不知技术上是否能实现）

**Comment by lizheming** [comment]
- [ ]这个可以做的，在用户列表里可以加一个每个成员拥有的文章数量，我之后加一下，非常赞。
- [-]文章总体数量的柱状图暂时不加到系统里头来，不过是个非常好的建议，以后做插件的时候可以做。
- [ ]阅读数量现在还没有单独的统计，这个也是可以做的，我需要考虑下增加到后期的开发中。评论数量这个不太好控制，如果你用的多说或者 Disqus 的话还好，其它的服务我们暂时还没去做获取评论数的功能，不过可以先暂时做出来，也可以放到用户管理的列表中作为数据展示出来。
