### ISSUE TITLE
文章模板

### ISSUE THREAD

**Issue by blackfader** [75team/firekylin#219]
虽说markdown格式很方便，但是有些重复性的内容有个模板就更好了，比如结尾插入的图片和介绍等。

**Comment by lizheming** [comment]
嗯，这个是有计划的，每个主题之后会增加主题模板功能，设置之后可以替换掉默认的文章模板和页面模板 https://github.com/75team/firekylin/projects/2#card-1040123。

目前的话你可以直接去修改主题默认模板实现，不过是需要一点前端知识了…

**Comment by lizheming** [comment]
另外如果你只是想要在文章后面插点固定内容的话，可以使用 外观设置-主题管理 里面的版权信息功能，在那里添加的内容目前会固定显示在文章后面。

**Comment by lizheming** [comment]
已经增加页面模板功能了，不过你的需求使用主题管理的版权信息就可以了~
