### ISSUE TITLE
这项目咋没有奇舞团其他人恭喜代码呢？感觉主要是一个人更新

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#220]
这项目咋没有奇舞团其他人恭喜代码呢？感觉主要是一个人更新

**Comment by lizheming** [comment]
刚开始开发的时候还是有很多人帮忙的，现在稍微稳定点了大家就干别的去啦，毕竟都很忙嘛 =w= 不过现在已经有很多热心的用户给我们提 PR 了，也欢迎你呀~
