### ISSUE TITLE
页面列表Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by fan-haobai** [75team/firekylin#221]
0.14.4版本，点击页面管理中的页面列表，会出现”Origin is not allowed by Access-Control-Allow-Origin“错误。

**Comment by lizheming** [comment]
只有这个页面会么？重启下服务试试？

**Comment by fan-haobai** [comment]
就这个页面有这个问题。我都重新安装npm了，第一次点击页面管理没问题，后面点击就会报这个错。

**Comment by fan-haobai** [comment]
@lizheming 就这个页面有这个问题。我都重新安装npm了，第一次点击页面管理没问题，后面点击就会报这个错。

**Comment by lizheming** [comment]
@fan-haobai 介意给我创建个账号我去后台看看么，我的邮箱 i@imnerd.org。

**Comment by fan-haobai** [comment]
@lizheming 已发邮箱。

**Comment by lizheming** [comment]
看了下，应该是接口报错了，单独访问接口有时候会报 `net::ERR_INCOMPLETE_CHUNKED_ENCODING` 的错误，我搜了下好像是 Chrome 的锅。你用别的浏览器试一下，我用 Firefox 刷了好几遍是正常的。如果确认是 Chrome 的问题的话，你 nginx 开个 gzip 应该就没有问题了。

不过也是我的锅，列表页没事返回页面的正文干嘛...我之后也改下吧…

**Comment by fan-haobai** [comment]
恩。我重新替换一下文件试试。

**Comment by lizheming** [comment]
咦？重新替换文件？不是说设置下 nginx 开启 gzip 么...

**Comment by fan-haobai** [comment]
我nginx开启了gzip。

**Comment by lizheming** [comment]
我刚才看的时候是没有 gzip 的，现在是502了...

**Comment by fan-haobai** [comment]
我正在重新装。node没启，所以502了。
