### ISSUE TITLE
在纠结使用 firekylin 还是 ghost  😅

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#222]
ghost 0.x 成熟度还算可以，默认主题 casper 也精美，有众筹资金起步，目前有团队在开发。缺点就是升级麻烦，开发缓慢，几年来没什么重大突破，且未来的 1.x 打算抛弃 markdown

frekylin  优点是国产化，升级还算方便。但撰写的舒适度不如 ghost，默认主题感觉不如 casper ，且主要是你在维护，担心你一年半载后你找了女票或老婆后就抛弃了这项目啊😁

**Comment by lizheming** [comment]
编辑器我还在努力优化，有什么问题可以说，不过我个人觉得还挺方便的。主题这个仁者见仁智者见智，感兴趣的话你完全可以自己 copy 主题过来，毕竟支持自定义主题功能… 后面这个没法接啊....
在我们的地盘问这种问题我当然会毫不犹豫的说自家产品嘛 =w= 总之项目我们是会一直维护下去的，肯定是会有人接盘的放心吧，哈哈哈~
