### ISSUE TITLE
页面编辑无法显示原先内容

### ISSUE THREAD

**Issue by NewpTone** [75team/firekylin#224]
在“页面管理”中，选定某一页面点击“编辑”，在编辑器中显示内容为空，无法编辑原先的内容，从日志中没有看到报错信息，查了下数据库，发现页面数据存在fk_post表中，是设计成page不允许更新吗，还是配置问题？

**Comment by lizheming** [comment]
其实。。。。就是个bug 😅

**Comment by NewpTone** [comment]
需要把这个bugfix cherrypick回稳定版本0.15.0吧？ 我试了一下，我是没法提交修改tag的pull request的。

**Comment by lizheming** [comment]
版本升级不就是为了解决 bug 么，如果还要 cherrypick 回 0.15.0 的话那还要升级版本干嘛呢？

**Comment by NewpTone** [comment]
我想说的是主分支的bugfix需要backport回稳定分支，和你说的意思一样，我已经看到0.15.1版本了，赞效率

**Comment by lizheming** [comment]
嗯 =w= 客气~ 现在 Firekylin 还在开发中…而且也没那么多人力去维护 LTS 版本，所以只有一个主分支~ 大家尽量都跟着升级就好了T_T
