### ISSUE TITLE
编辑器的几个建议

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#225]
首先感谢公子的努力付出。

我在 [itlaws.cn](https://itlaws.cn) 安装的是最新的 0.15.1 ，发现编辑器有这些需要改善的地方：

- [x] 右分栏不能跟随左分栏滚屏，写长文章时，这点很重要。
- [x] 右分栏不能实时预览 `* ` 或 `- ` 之类的列表

https://pandao.github.io/editor.md/ 这个编辑器就做得很不错，支持左右分栏自动同步滚动。

**Comment by lizheming** [comment]
列表只是个样式的问题我修改一下，同滚我加一下吧，之前一直没加是因为觉得没有完美的左右同滚。
