### ISSUE TITLE
版本太老 升级有啥注意的 

### ISSUE THREAD

**Issue by Jerret321** [75team/firekylin#234]
从0.14.0升级到最新版 一直install， install会不会把老的库给覆盖掉？如果会，怎么做平滑升级。 
另外还有其他的要注意的吗？ 谢谢~

**Comment by lizheming** [comment]
是手动升级的还是在线升级的，看下根目录下 `.installed` 这个文件，没有的话新建一个就好了

**Comment by Jerret321** [comment]
手动升级搞定了 自己升级把文件覆盖了

**Comment by lizheming** [comment]
OK

**Comment by lizheming** [comment]
0.14.0+ 后自带在线更新功能，后台可一键更新，建议尽量使用在线更新功能哈~

**Comment by Jerret321** [comment]
@lizheming 好的~

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/wiki/%E6%9B%B4%E6%96%B0 刚补全了一下升级的 wiki 可参考一下。

**Comment by Jerret321** [comment]
可以把升级过程中 遇到问题wiki列表放一下 这样其他同学直接能找到了

**Comment by lizheming** [comment]
嗯，欢迎补充
