### ISSUE TITLE
忘记密码怎么办

### ISSUE THREAD

**Issue by mignetwee** [75team/firekylin#237]
请问如果管理员密码忘记了，怎么才能重置密码啊

**Comment by lizheming** [comment]
[忘记密码怎么办？](https://github.com/75team/firekylin/wiki/%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#%E5%BF%98%E8%AE%B0%E5%AF%86%E7%A0%81%E6%80%8E%E4%B9%88%E5%8A%9E)
