### ISSUE TITLE
用户权限问题-审核

### ISSUE THREAD

**Issue by blackfader** [75team/firekylin#243]
目前角色分为 管理员 编辑 投稿者
目前有这样一个问题，资深编辑发布文章可以不用审核，小白编辑最好有老编辑审核一下给把把关，不知道如何解决好。

**Comment by lizheming** [comment]
目前管理员是不需要审核直接发布的，编辑可以直接在后台写文章但需要审核才能发布，投稿者不能进入网站后台，只能推送文章，推送的文章也是需要审核发布的。

资深编辑的话可以使用管理员权限，小白编辑则使用编辑权限即可实现你说的效果。之前的版本中如果编辑修改文章会直接发布文章的 bug 已经在 https://github.com/75team/firekylin/commit/93089ecc706a2d17327503698c977630238343ac 该 commit 中修复，感谢！
