### ISSUE TITLE
使用 yarn 安装依赖报错（to-markdown 依赖的 node 版本号问题）

### ISSUE THREAD

**Issue by jerrybendy** [75team/firekylin#244]
你好，

我的环境是 NodeJS 6.9，yarn 0.21.3。

在使用 yarn 安装依赖时报错，大致内容是说，项目中依赖的 `to-markdown` 要求 Node 的版本是 `^4`，实际是 6.9，与预期版本不符，导致依赖无法安装。然后尝试使用 npm 安装依赖并未报此错误。

看了下 `to-markdown` 的仓库，在 2015 年 10 月发布的 2.0.1 版本及 2016 年 3 月发布的 2.1.0 版本中的 engine 都是写的 `^4`，而最新版本的 3.0.3 是改成了 `>=4`。

所以修复这个问题最直接的方式就是升级依赖至最新版本，但 3.x 和 2.x 之间可能会有接口的调整。不知是否计划修复这项问题。

谢谢

**Comment by lizheming** [comment]
感谢提醒，我看了下 3.x 和 2.x 的接口没有太大变化，已直接升级了，谢谢。

**Comment by jerrybendy** [comment]
嗯，谢谢。

另外，db 目录下 4 月 8 日的 sql 文件，似乎是把测试的数据库弄上来了，里面好多文章数据～

**Comment by lizheming** [comment]
故意的，开发默认填充数据，安装版是不会有的。

**Comment by jerrybendy** [comment]
哦，好的 😁
