### ISSUE TITLE
后台文章编辑优化

### ISSUE THREAD

**Issue by blackfader** [75team/firekylin#246]
后台文章编辑优化优化呗
比如 

- [x] 增加字数显示
- [ ] md的树形结构
- [ ] 预览栏动态滚动

**Comment by lizheming** [comment]
数字显示可以加，不过并不觉得意义很大，树形结构在显示页支持了，编辑页就不支持了。同滚已经在规划中了 #225

**Comment by blackfader** [comment]
对于作者还是挺关心码了多少字的，要考虑读者能看多少
