### ISSUE TITLE
邮件订阅功能

### ISSUE THREAD

**Issue by blackfader** [75team/firekylin#247]
增加个邮件订阅功能怎么样？RSS那种很多人都不会用，最好简单的输入邮件地址就完成。

**Comment by lizheming** [comment]
有很多服务可以将 RSS 以邮箱的形式订阅的额... 比如 http://blogtrottr.com/   
另外QQ邮箱的阅读空间自带 RSS 订阅功能  
如果自己做邮箱订阅的话你发一篇文章就要往所有的邮箱发消息，先不说自建邮箱会被人当成垃圾邮件等诸如复杂无解的问题，就说如果订阅人一多你的服务器的鸭梨就够呛了。
