### ISSUE TITLE
李冬杰的博客

### ISSUE THREAD

**Issue by BezosLee** [75team/firekylin#251]
[www.makeco.cn](http://www.makeco.cn/)

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/issues/34 在这个 issue 评论里加一下吧，不用单独开一个 issue 了，谢谢~

**Comment by BezosLee** [comment]
如果你不希望在聚合中输出文章全文,请使用仅输出摘要选项.摘要的文字取决于你在文章中使用*分隔符*的位置.

请问分割符是啥？

**Comment by lizheming** [comment]
`<!--more-->`
