### ISSUE TITLE
多说要关闭了…「无具体问题」

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#256]
『多说将于2017年6月1日正式关停服务，在此之前您可以通过后台的数据导出功能导出自己站点的评论数据。感谢您的一路相伴。』

多说冷寂了几年后终于要走了。感觉中外的文化偏好完全不同，国外重分工与专业化，中国重大而全，既然自己搞了博客就不愿意把评论托管到第三方。

或者说，国内这个专业细分无法撑起一个盈利模式。有些大厂心血来潮时会贴钱做类似的项目，但也说不定哪天就把项目砍了。

**Comment by lizheming** [comment]
嗯，好在我有先见之明增加了畅言的支持，之后又增加了网易云跟帖的支持，另外还有一片多说数据迁移指南仅供参考：https://imnerd.org/firekylin-duoshuo-migration.html。

**Comment by choicky** [comment]
@lizheming 干脆给 firekylin 加个评论模块吧 ^_^

**Comment by qgy18** [comment]
@lizheming 你给的链接之后的句号也被识别为 url 的一部分，所以 404 了。😂

**Comment by lizheming** [comment]
@qgy18 😂 惨惨惨，句号太小没看粗来，已修改~
