### ISSUE TITLE
关于编辑主题页面的问题

### ISSUE THREAD

**Issue by snadn** [75team/firekylin#257]
首先，编辑主题页面无法打开，调试了一下，发现依赖的 react-treebeard@1.1.4 组件依赖了 radium@0.18，而该组件依赖 react@15.3 以上，但 firekylin 依赖的是 react@0.14。 FormidableLabs/radium#884

其次，admin/api/theme 接口有严重的安全风险，通过相对路径可以访问到系统任意的文件。

ps：看了一下依赖，部分依赖的组件比较陈旧了啊。

**Comment by lizheming** [comment]
ps: react 全家桶不敢升....

**Comment by snadn** [comment]
更新确实痛苦，深有体会……但不升也确实有很多问题……很矛盾的……

**Comment by lizheming** [comment]
目前后台整体依赖了 react-bootstrap 这个样式组件...这组件新版 API 全改了....所以没法升....其它的一些不依赖的倒是可以选择性升级一下，我看看吧。

**Comment by lizheming** [comment]
fix at https://github.com/75team/firekylin/commit/dcd4e9fdc47a0e807b8b5e4fc46af430aa2fd911 and https://github.com/75team/firekylin/commit/8905aa394f14a843c4db675203e36f026fe39fa0
