### ISSUE TITLE
页面不存在但status_code为200的问题

### ISSUE THREAD

**Issue by yeahx** [75team/firekylin#260]
![image](https://cloud.githubusercontent.com/assets/11347901/24291008/26b70070-10c2-11e7-88d3-3e4ffd6f5f2f.png)

问题如上图访问一个不存在的html页面发现firekylin返回的status_code为200

**Comment by lizheming** [comment]
这个是故意的，为了防止有些运营商劫持 404 状态码，所以都用了 200。可以看百度和QQ的，他们的状态码也都是200

**Comment by yeahx** [comment]
涨姿势了，国内网络环境好复杂~
谢谢！
