### ISSUE TITLE
请问为什么 PORT 不通过环境变量的方式获取？

### ISSUE THREAD

**Issue by ddhhz** [75team/firekylin#261]
如题：请问用文件系统来控制端口号是什么原因？

一般的 Node app 都会通过 process.env.PORT 环境变量来获取。

谢谢！

**Comment by lizheming** [comment]
方便一环境部署多个嘛

**Comment by ddhhz** [comment]
@lizheming 谢谢你的快速回复哈。

根据 [Docs](http://pm2.keymetrics.io/docs/usage/application-declaration/) 可以通过 env 在 Process File 设置。

```json
{
  "apps": [{
    "name": "firekylin",
    "script": "www/production.js",
    "cwd": "/Users/welefen/Develop/git/firekylin",
    "exec_mode": "fork",
    "max_memory_restart": "1G",
    "autorestart": true,
    "node_args": [],
    "args": [],
    "env": {
      "PORT":8080
    }
  }]
}
```

也可以直接 `$ PORT=8080 pm2 start www/production.js` 运行哈。

部署到一些 Managed Environments 里会要求 Node.js app honor 这个环境变量。

**Comment by lizheming** [comment]
其实都一样，要加上也不麻烦，如果你觉得有必要的话欢迎 pr 加一下 😋

**Comment by ddhhz** [comment]
@lizheming 好呀好呀，我在模仿 Docker Hub 里 WordPress 官方镜像做一个 Firekylin 的。如果用环境变量的话会方便很多。

请问需要保留从文件读取 PORT 的功能吗？如果需要请问你觉得哪个应该优先呢？

谢谢🙏 ！

**Comment by lizheming** [comment]
保留吧，要不然以前老版本没办法了都，我觉得以文件优先吧，PORT 怕其他 node 程序会占用了呢。
