### ISSUE TITLE
数据库连接判断部分有问题

### ISSUE THREAD

**Issue by solarhell** [75team/firekylin#36]
安装时填写了远程数据库 但是程序会自动连接写死在配置文件中的 127.0.0.1:3306
![log](https://cloud.githubusercontent.com/assets/10279583/13808500/4a8dd2a4-eba1-11e5-9a42-ff9b3c8c3cbe.png)

**Comment by welefen** [comment]
是在安装界面里填的？

看下 app/common/config/db.js 里配置具体是什么

**Comment by solarhell** [comment]
是在安装界面填的 配置文件中也是正确的
![qq20160316-0](https://cloud.githubusercontent.com/assets/10279583/13808915/58686d92-eba3-11e5-9b0e-e335152d5359.png)

**Comment by welefen** [comment]
已经修复，请下载最新的安装包更新下。

**Comment by solarhell** [comment]
安装方式应该更优雅，不用每次都下载安装包再解压。建议新建一个`release brach`来发布最新的生产代码，这样每次更新`git pull`一下就行了。

**Comment by welefen** [comment]
@solarhell  这个建议不错，后续可以考虑
