### ISSUE TITLE
现在markdown编辑器,图片预览有问题

### ISSUE THREAD

**Issue by xueyuchen** [75team/firekylin#38]
1. 上传图片后，markdown编辑界没有自动添加图片链接的代码
2. 在上述操作后，继续在markdown编辑器界面中添加文字，预览界面无法同步
3. 多次上传图片后，发布文章，查看文章没有之前上传的图片

**Comment by lizheming** [comment]
第一个问题已经修复了，你可以下最新版的试试。
后面两个我猜测可能是由于第一个的问题导致的，你可以再试试，如果不行的话可以继续 reopen 这个 issue。谢谢！
