### ISSUE TITLE
页面安装显示：Error: Cannot enqueue Query after invoking quit.

### ISSUE THREAD

**Issue by linqq** [75team/firekylin#45]
安装的提示如下错误
![image](https://cloud.githubusercontent.com/assets/4436031/13873028/b3fc33fa-ed29-11e5-9475-cc8351905c45.png)

**Comment by welefen** [comment]
已经修复了，下载最新的包重新安装下。

**Comment by linqq** [comment]
下载最新包问题依然存在！

**Comment by telfordNiu** [comment]
昨天下的包，也有同样的问题！

**Comment by welefen** [comment]
现在重新下载下试试
