### ISSUE TITLE
utf8mb4字符集兼容问题

### ISSUE THREAD

**Issue by wd4blue** [75team/firekylin#58]
我的msyql5.1默认不支持utf8mb4字符集编码，建议将默认字符集编码改成utf8。在特殊需求情况之下需要使用utf8mb4提醒用户升级支持

**Comment by lizheming** [comment]
还要去判断特殊需求…那么麻烦直接升级你的 MySQL 不就好了…=_=!

**Comment by welefen** [comment]
可以考虑默认的字符编码还是改为 utf8，有需要的话自己修改为 utf8mb4

**Comment by welefen** [comment]
已经将默认的字符集改为 utf8
