### ISSUE TITLE
管理后台导航栏点击状态变化突兀

### ISSUE THREAD

**Issue by wd4blue** [75team/firekylin#59]
例如页面管理是展开的状态下，点击分类管理。建议增加页面管理折叠与分类管理展开的动画。

**Comment by welefen** [comment]
左侧切换的时候可以加个动画

**Comment by lizheming** [comment]
https://github.com/75team/firekylin/commit/7dab98179df11ad4cf1058562ad85fa64c5dd109 
嘤嘤嘤，commit 写错 issue id 了，手动关联一下T_T
