### ISSUE TITLE
管理后台帐户密码重置

### ISSUE THREAD

**Issue by justfbt** [75team/firekylin#62]
请问我的后台帐户密码忘记了，怎么样重置密码？（mysql）

**Comment by lizheming** [comment]
如果有另外一个管理员账号的话可以让他帮你重置一下。如果没有的话可以先清空 user 表，然后删除项目根目录下的 `.installed` 文件，重新安装一下。记得先备份一下数据~

**Comment by justfbt** [comment]
经测：清空表并删除.installed文件后还要重启服务才能重新到安装界面。

问题是我已经重新安装多次，登录后台时一直都提示我“用户名或密码错误”
查数据库：
mysql> select name,password from fk_user;
+-------+--------------------------------------------------------------+
| name  | password                                                     |
+-------+--------------------------------------------------------------+
| admin | $2a$08$R/Hxxxxxxxxxxxxxxue/MnmCN2Tcl7DcnnMG |
+-------+--------------------------------------------------------------+
1 row in set (0.00 sec)

不知什么原因。  求解

**Comment by lizheming** [comment]
已经修好了，是因为导入数据库表的问题，等新版本发布吧！
