### ISSUE TITLE
安装成功后，后台登录一直提示“用户名或密码错误”

### ISSUE THREAD

**Issue by telfordNiu** [75team/firekylin#64]
安装成功后，后台进入不了，一直提示“用户名或密码错误”，确定用户名和密码没有错，为此还重新安装过。求解！

**Comment by justfbt** [comment]
我遇到的情况和你一样！ 目前还没解决！
https://github.com/75team/firekylin/issues/62

**Comment by telfordNiu** [comment]
暂时可以用起来的一种笨方法，绕过密码验证。进入app/admin/controller下的user.js
userModel.checkPassword(userInfo, password)改为!userModel.checkPassword(userInfo, password)
然后保存，进入后台后修改密码再把!去掉，保存后，重新登录就可以了！

初步判断是安装初始时的密码加密后，与后台登录密码加密验证有问题。

**Comment by aztack** [comment]
same problem

**Comment by lizheming** [comment]
同 #62 已经修复了，等新版发布吧！感谢各位~

**Comment by dangyanglim** [comment]
我直接clone安装的还有这个问题

**Comment by lizheming** [comment]
@dangyanglim 使用安装版安装吧，http://firekylin.org/release/latest.tar.gz。仓库的是开发版，不推荐使用这个版本安装。
