### ISSUE TITLE
apache.conf 能提供一下吗

### ISSUE THREAD

**Issue by telfordNiu** [75team/firekylin#66]
apache.conf能提供一下吗？利用apache代理成功后，文章中有链接出现127.0.0.1:8360,
另外还有一个问题修改端口后，网站基础配置的信息都没有了！还要重新填写！！

**Comment by lizheming** [comment]
链接是哪个链接，能具体说一下么，因为我们是不会记录你的地址的，一般都是根据你的访问地址来决定的。
基础配置是什么意思？是后台系统设置么？你是怎么修改的端口？修改端口是在根目录下新建一个 port 文件。

**Comment by telfordNiu** [comment]
是网站的基本信息，在后台填写好后，如果修改了port端口，然后再访问网站，基本信息就没有了，还需要再重新填写。

**Comment by lizheming** [comment]
链接是哪个链接？port 是怎么修改的？好像都没有回答啊…
最后你更新到 0.5 版导入下 0.5 的数据库吧，感觉你说的问题在 0.5 已经解决了。

**Comment by telfordNiu** [comment]
刚刚下了0.5的，问题已经解决，谢谢！
