### ISSUE TITLE
当 User-Agent 为空时，直接 500 了

### ISSUE THREAD

**Issue by qgy18** [75team/firekylin#68]
无意中发现的，例如：

```bash
curl -I -H'User-Agent: ' http://www.welefen.com

HTTP/1.1 500 Internal Server Error
Server: nginx/1.9.9
Date: Tue, 05 Apr 2016 12:53:33 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Powered-By: thinkjs-2.1.8
```

**Comment by lizheming** [comment]
1. 直接测试端口故障依旧证明不是 nginx 的锅
2. 测试直接 curl 本地的 firekylin 是没有这个问题的
3. 测试了 cicada/thinkjs.org 两个网站，发现没有这个问题，看起来不像是 thinkjs 的问题
4. 故障具体表现为 UA 为空或者为一系列空字符串的时候都会有这个问题

看了下 firekylin 的源码，首页的 Controller 很简单，应该没啥问题，等成银来看看吧..

**Comment by qgy18** [comment]
找到原因了，编译后的 `www/theme/firekylin/layout.html` 文件中有这么一行：

```
{% if http.userAgent().indexOf("MSIE ") == -1 and not http.cookie("stc_nls")%}
```

**Comment by lizheming** [comment]
感觉少了个括号？按道理不应该是 `http["userAgent"]()["indexOf"]` 么？

**Comment by welefen** [comment]
已经加了判断了。
