### ISSUE TITLE
iPhone safari 中列表页链接无法点击

### ISSUE THREAD

**Issue by qgy18** [75team/firekylin#69]
非常诡异。

用 iPhone 的 safari 打开使用火麒麟的博客，点击列表页内容中的链接，例如下图的 `thinkjs`，会直接跳转到 `/null` 页，提示 404。

![15 pic](https://cloud.githubusercontent.com/assets/285369/14282535/65804666-fb71-11e5-998d-f5d14fdc8750.jpg)

电脑上没这个问题，点击「标题或阅读全文」也没问题。

**Comment by qgy18** [comment]
感觉问题出在这里：

```javascript
    for( var i = 0 ; i < this.$article.length; i++ ){
      this.$article[i].addEventListener( 'click' , function(){
        var url = this.getAttribute('data-url');
        window.location.href = url ;
      },false);
    }
```

**Comment by lizheming** [comment]
是的，就是这个问题... 不过很好奇为什么只有在手机端才会出现这个问题...
