### ISSUE TITLE
评论权限问题

### ISSUE THREAD

**Issue by liurq** [75team/firekylin#75]
0.6版本 我设置了  允许评论  但是保存时却还是没有评论权限，进来修改时是没选中的，选中了保存再进来还是没选中，我进数据库手动改fk_post allow_comment字段值为1才可以

**Comment by welefen** [comment]
你是刚刚下的 0.6 版本么？ 重新下下覆盖试试

**Comment by liurq** [comment]
刚重新下了覆盖了一下，现在ok了
