### ISSUE TITLE
文章管理列表一直加载中

### ISSUE THREAD

**Issue by shuchengliang** [75team/firekylin#77]
![image](https://cloud.githubusercontent.com/assets/2794666/14523073/48257cc2-0264-11e6-9b95-ec2741e35679.png)
报错如下
![image](https://cloud.githubusercontent.com/assets/2794666/14523092/625ba030-0264-11e6-9363-e606003afa61.png)
代码都是没有动过的。

**Comment by welefen** [comment]
是因为用了 ES6 方法但没引入 `babel-polyfill` 导致的，请升级到 0.7.0 版本。
