### ISSUE TITLE
增加“网站维护中”页面

### ISSUE THREAD

**Issue by aztack** [75team/firekylin#79]
nginx.conf中增加相应设置；www下增加“维护中”静态页面；

**Comment by lizheming** [comment]
为啥要加这个？

**Comment by aztack** [comment]
只是为了方便维护。所以提的是enhancement，不是bug。

**Comment by lizheming** [comment]
这种东西自己加就好了吧，不是所有用火麒麟的都要用的刚需。

**Comment by qgy18** [comment]
如果火麒麟能支持插件机制，这种就可以做成一个插件了，放在主版本里确实用得太少。

**Comment by lizheming** [comment]
@qgy18 是的，插件和多主题的机制我们也在考虑怎么弄，这肯定是要加上的。
