### ISSUE TITLE
bae部署，这临时文件都丢失了。

### ISSUE THREAD

**Issue by wl496928838** [75team/firekylin#80]
诸如文章里面的图片，头像，安装信息，等等。在BAE重启以后都没有了。
并且。数据库如果已经存在表，居然给覆盖了。。。数据都丢了~~
能否开发 OSS 或者 七牛的储存文件的方式~

**Comment by lizheming** [comment]
BAE 应该是不支持本地文件的直接读写的吧？数据库这个后期我们会专门导出一个升级专用 SQL 的，安装的时候 drop 主要是结构不稳定怕有人还用了老数据库结构。上传的话以后增加了插件支持会以插件的形式加上这些功能的，目前主程序暂时不打算增加这些功能，抱歉！

**Comment by wl496928838** [comment]
bae支持临时写入,重启 或者 更新代码 就会 清空临时文件..

目前转投 hexo

http://blog.c2567.com/

哈哈~~

**Comment by wl496928838** [comment]
支持阿里云oss或者七牛oss,可用性更强..速度也比较快.

**Comment by wl496928838** [comment]
阿里云有nodejs的 demo 我试过的,集成起来应该方便~如果不做权限管理的话..

**Comment by lizheming** [comment]
*AE 这种环境都比较特殊需要做特别处理，不是刚需的功能通过插件支持是比较方便的方法。云存储可以加入，但是应该是以插件的形式加上而不是程序本身自带，因为这些服务有些人根本不用，如果说使用你的博客系统还要强制别人去使用哪一家的服务，也会引来非议。anyway，还是非常感谢你的建议！

**Comment by wl496928838** [comment]
对，就是加一个插件，hook上传的函数，中转到 第三方储存。
