### ISSUE TITLE
如何去掉本文链接的端口

### ISSUE THREAD

**Issue by liurq** [75team/firekylin#81]
在博客内容最下面有个：

本文链接：http://xx.com:端口/post/num.html
— EOF —
这个端口咋去掉？

在nginx中监听了nginx的80端口， node的8888端口
在nginx.conf中做了代理了

本文链接实际上应该是http://xx.com/post/num.html 才对的

**Comment by liurq** [comment]
等我弄好这个博客，再把网址提交到https://github.com/75team/firekylin/issues/34 上

**Comment by lizheming** [comment]
后台基础配置里面有个网站地址的配置，你去修改一下这个地址吧。
