### ISSUE TITLE
多说评论支持HTTPS

### ISSUE THREAD

**Issue by akira-cn** [75team/firekylin#83]
建议把多说js改一下，头像和表情替换成dataURI

**Comment by akira-cn** [comment]
https://imququ.com/post/duoshuo-and-https.html

**Comment by akira-cn** [comment]
按屈屈这个改一下吧

**Comment by lizheming** [comment]
@akira-cn 屈屈这个要做反代，要写 nginx 配置神马的，万一用户用的不是我们给的 nginx 配置岂不是…

**Comment by qgy18** [comment]
多说这个确实比较头痛。多说自己的资源都已经支持 https 了，主要是微博、人人什么的第三方登录后头像还是 http 的。

还是推荐用 disqus。

On Wed, May 4, 2016 at 1:46 PM, 公子 <notifications@github.com> wrote:

> @akira-cn <https://github.com/akira-cn> 屈屈这个要做反代，要写 nginx
> 配置神马的，万一用户用的不是我们给的 nginx 配置岂不是…
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/75team/firekylin/issues/83#issuecomment-216750541>
>



-- 
非常感谢~

屈光宇（ImQuQu.com）

**Comment by akira-cn** [comment]
那就增加一个自定义评论的选项，现在只能默认选择多说和disqus，增加一个自定义评论，就可以自己添加评论代码……

**Comment by akira-cn** [comment]
我在统计代码那里加了js来hack，暂时弄好了……

**Comment by lizheming** [comment]
自定义评论这个可以有~我来加下试试。

**Comment by lizheming** [comment]
自定义评论加上啦，不过有一个问题，thread-key 现在用的是 md5(url) 好像，自定义评论的话要自己写 DOM 所以不会算这个…=_=! 好蛋疼…
