### ISSUE TITLE
有两个问题想请教下

### ISSUE THREAD

**Issue by gdhzkk** [75team/firekylin#84]
1.url可以自动生成吗？比如数字从1开始自动生成；
2.可以增加个评论功能嘛，喜欢系统自带的。

**Comment by lizheming** [comment]
1. 这个可以考虑一下
2. 评论做起来比较复杂，短时间应该不会去做，而且社会化评论也有它的好处。

**Comment by lizheming** [comment]
想了下 1. 这个可能不太好加，因为现在 firekylin 的文章创建后 pathname 就不可编辑了，如果使用 id 的话就没办法更改了。而且 firekylin 有文章推送功能，pathname 如果使用 id 的话会导致推送文章的 id 重复出现文章覆盖的现象，需要再考虑下里面的逻辑。

**Comment by gdhzkk** [comment]
不生成id，生成随机的数字也好的，每个都要手动添加有点麻烦，另外分类能不能选一个做默认的并勾选它？

**Comment by lizheming** [comment]
生成随机数字也是一个逻辑的，这个需要习惯。分类增加默认这个可以有，应该没有问题。

**Comment by welefen** [comment]
数字 ID 的 URL 不够语义，也不利于 SEO。

**Comment by lizheming** [comment]
你好，默认分类的设置已经加上了，其它两个暂时没这个计划我就先暂时把这个 issue 关闭了，后续有什么问题可以继续提出来。
