### ISSUE TITLE
在本地测试为什么很慢页面一直在加载中？

### ISSUE THREAD

**Issue by gdhzkk** [75team/firekylin#85]
系统: win10;
node: v5.10.1;
通过 npm start 启动项目后，刚开始一会运行正常，过一会在点击链接或刷新页面就一直加载中，前台后台都会一直加载中，重启项目又好了，过一会又出现这个问题了，昨天安装的但没发现有问题，今天才出现的。

[2016-05-06 09:35:40] [HTTP] GET /archives/ 200 272191ms

**Comment by lizheming** [comment]
在其他环境中测试了么...我这没办法复现…

**Comment by gdhzkk** [comment]
没在其它环境测试，安装过几个node项目 只有firekylin会出现这个问题，可能是win上测试的关系吧

**Comment by lizheming** [comment]
那你要不帮忙多测一下？很多用户都用 firekylin 只有你报出现这个问题~
