### ISSUE TITLE
推送过来的文章在头部加上原文链接

### ISSUE THREAD

**Issue by welefen** [75team/firekylin#86]
RT，这样可以知道文章来源

**Comment by lizheming** [comment]
已经加上了，本来应该在接收方这边做会比较好一点（可以比较方便的显示作者昵称），但是考虑到已经有用户推送过文章了，所以还是在推送方这边做，这样想要加上头的话直接重新发布下文章就好了，而不用在意对方的版本支不支持。

**Comment by welefen** [comment]
恩，就在发送方做。接收方并不知道发送方的域名，不然还要加参数。
