### ISSUE TITLE
几个细节问题

### ISSUE THREAD

**Issue by wavelynn** [75team/firekylin#90]
1. pathname 存在直接提示PATHNAME_EXIST
2. 投稿者是否有权限删除自己的文章？目前实现应该是没有权限，但是展示了删除按钮。
3. 投稿者是否有权限删除草稿文章？目前实现是没有权限?
4. 投稿者的文章列表是否需要已发布 审核中 已拒绝？

其他用户组比如编辑者是否有相同问题？

**Comment by lizheming** [comment]
2 和 3 是一个问题，都已经修复。4 是不需要的，审核和拒绝是要对其它人的文章进行操作的，编辑只能对自己的文章进行操作。
